implement hylafax classes
kopiLeft/Galite pull request #100
Opened 2020-11-04 17:02 UTC by SNsir

2020-11-05 10:52 UTC, ZMarouani requested changes

2020-11-05 10:52 UTC, ZMarouani commented on galite-core/src/main/kotlin/org/kopi/galite/util/PlatformFileWriter.kt
> +  // ----------------------------------------------------------------------
Constructors should be like this : 
class PlatformFileWriter(val dataStream: OutputStream,
                         val encoding: String,
                         val lineSeparator: String) {
  /**
   * Sets the number of copy to print
   */
  constructor(file: File,
              encoding: String,
              lineSeparator: String) : this(FileOutputStream(file) , encoding , lineSeparator  ) 
  
  constructor(fileName: String,
              encoding: String,
              lineSeparator: String) : this(File(fileName), encoding, lineSeparator)

2020-11-05 10:52 UTC, ZMarouani commented on galite-core/src/main/kotlin/org/kopi/galite/util/PlatformFileWriter.kt
> +  private val dataStream: OutputStream
Delete

2020-11-05 11:19 UTC, SNsir commented on galite-core/src/main/kotlin/org/kopi/galite/form/VTextField.kt
> +
yes ignore it, we will not implement it

2020-11-05 11:23 UTC, SNsir commented on galite-core/src/main/kotlin/org/kopi/galite/util/Fax.kt
> + */
already done in PR#92 , ignore it here

2020-11-06 09:53 UTC, ZMarouani approved these changes

2020-11-06 11:16 UTC, merged