Adding ALIGN property to block
kopiLeft/Galite pull request #132
Opened 2020-11-20 09:39 UTC by h-haddad

2020-11-30 11:28 UTC, ZMarouani requested changes

2020-11-30 11:28 UTC, ZMarouani commented on galite-core/src/main/kotlin/org/kopi/galite/form/dsl/FormBlockAlign.kt
> +  }
Please document this method ( referenced from "genCode(Vector body)" in VKBlockAlign class in Kopi )

2020-12-04 08:16 UTC, ZMarouani commented on galite-core/src/main/kotlin/org/kopi/galite/base/t.kt
> +}
Add line

2020-12-20 21:51 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/base/t.kt
> +}
what this class is for ?!

2021-04-02 15:26 UTC, SNsir approved these changes

2021-04-02 15:41 UTC, SNsir approved these changes

2021-04-05 08:36 UTC, hfazai approved these changes

2021-04-05 08:36 UTC, merged