add field droppable feature
kopiLeft/Galite pull request #149
Opened 2020-12-01 14:44 UTC by SNsir

2020-12-01 17:11 UTC, ZMarouani requested changes

2020-12-01 17:11 UTC, ZMarouani commented on galite-core/src/main/kotlin/org/kopi/galite/form/dsl/FormBlock.kt
> +  inline fun <reified T : Comparable<T>> initField(domain: Domain<T>,
The part to add the field with droppable is implemented insed the initField method with this part in line 1868 in FormParser.java  , but you will need to find alternatives for VKstringtype , VKImageType and reportTrouble() function  , afterwards the implementation will look like this : 

```javascript
    inline fun <reified T : Comparable<T>> initField(domain: Domain<T>,
                                                       init: FormField<T>.() -> Unit,
                                                       access: Int,
                                                       position: FormPosition? = null): FormField<T> {
        domain.kClass = T::class
        val field = FormField(this, domain, blockFields.size, access, position)
        field.init()
        field.setInfo()
    
        if (dropList == null) {
          blockFields.add(field)
        } else {
          if (type.getDef() !is VStringType
                  && type.getDef() !is VKImageType) {
            reportTrouble(PositionedError(sourceRef,
                    FormMessages.UNSUPPORTED_DROP_FIELD_TYPE,
                    name))
          } else {
            val flavor: String? = this.addDropList(dropList!!, field)
            if (flavor == null) {
              blockFields.add(field)
            } else {
              reportTrouble(PositionedError(sourceRef,
                      FormMessages.DUPLICATE_DROP_FLAVOR,
                      flavor,
                      this.dropListMap[flavor]))
            }
          }
        }
        return field
      }
```

2020-12-01 17:11 UTC, ZMarouani commented on galite-core/src/main/kotlin/org/kopi/galite/form/dsl/FormBlock.kt
> +  var dropListMap = HashMap<String, String>()
Also Add property :   var dropList : MutableList<String>? = null

2020-12-01 17:11 UTC, ZMarouani commented on galite-core/src/main/kotlin/org/kopi/galite/form/VBlock.kt
> +  protected var dropListMap = HashMap<String, String>()
I dont think we need to add this to VBlock

2020-12-01 17:11 UTC, ZMarouani commented on galite-core/src/main/kotlin/org/kopi/galite/form/dsl/FormBlock.kt
> +        }
We probably don't need this , we will recheck after implementing the other corrections

2020-12-03 09:49 UTC, ZMarouani approved these changes

2021-02-05 16:29 UTC, hfazai approved these changes

2021-02-05 16:30 UTC, merged