Implementation of getSearchConditions() in VBlock.kt with Exposed
kopiLeft/Galite pull request #152
Opened 2020-12-02 14:09 UTC by ZMarouani

2020-12-03 13:51 UTC, h-haddad commented on galite-core/src/main/kotlin/org/kopi/galite/form/VBlock.kt
>  package org.kopi.galite.form
merge class with master

2020-12-03 13:51 UTC, h-haddad commented on galite-core/src/main/kotlin/org/kopi/galite/form/VBlock.kt
> +  fun getSearchConditions(): Op<Boolean> {
i think that this method can return null value

2020-12-03 13:51 UTC, h-haddad commented on galite-core/src/main/kotlin/org/kopi/galite/form/VBlock.kt
> +          val condOperand : TypeVariable<GenericDeclaration> = vField.getSearchCondition_()!!.second
change condOperand to value

2020-12-03 13:51 UTC, h-haddad commented on galite-core/src/main/kotlin/org/kopi/galite/form/VBlock.kt
> +                  VarCharColumnType())
fix style

2020-12-03 13:51 UTC, h-haddad commented on galite-core/src/main/kotlin/org/kopi/galite/form/VField.kt
> +  open fun getSearchCondition_() : Pair<ExpressionWithColumnType<String>.(t: Any)-> Op<Boolean> , TypeVariable<GenericDeclaration>>? {
fix code style

2020-12-03 13:51 UTC, h-haddad commented on galite-core/src/main/kotlin/org/kopi/galite/form/VBlock.kt
> +    fields.forEach { vField ->
change vField to field

2020-12-03 13:51 UTC, h-haddad commented on galite-core/src/main/kotlin/org/kopi/galite/form/VBlock.kt
> +      if(vField.getColumnCount() > 0 ){
add empty space after if an before {

2020-12-03 13:51 UTC, h-haddad commented on galite-core/src/main/kotlin/org/kopi/galite/form/VBlock.kt
> +          val condOperand : TypeVariable<GenericDeclaration> = vField.getSearchCondition_()!!.second
remove : type

2020-12-04 10:13 UTC, h-haddad approved these changes

2020-12-08 14:47 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/form/VBlock.kt
> +                                                                     localRecordCount)
undo

2020-12-08 14:47 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/form/VBlock.kt
> +                                                            arrayOf<Any>(tables!![tableIndex])))
undo

2020-12-08 14:47 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/form/VBlock.kt
> +                                                              arrayOf<Any>(tables!![tableIndex])))
undo all reformat changes

2020-12-21 15:50 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/form/VBlock.kt
> +                localRecordCount)
undo

2020-12-21 15:50 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/form/VBlock.kt
> +            || !isMulti() && activeField == null) {
undo

2020-12-21 15:50 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/form/VBlock.kt
> +    return VBlockDefaultOuterJoin.getSearchTables(this)  }
undo

2020-12-21 15:50 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/form/VBlock.kt
> +          ReplaceWith("performAsyncAction(action)"))
undo

2020-12-21 15:50 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/form/VBlock.kt
> +              form.blocks.size == 1)
undo

2020-12-21 15:50 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/form/VField.kt
> +              toolTip)
undo

2020-12-21 15:50 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/form/VField.kt
> +            names)
undo

2020-12-21 15:50 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/form/VField.kt
> +  var toolTip : String? = null // help text
undo

2020-12-25 15:45 UTC, h-haddad requested changes

2020-12-28 16:01 UTC, ZMarouani commented on galite-core/src/main/kotlin/org/kopi/galite/form/VBlock.kt
> +          conditionList.add(condition)
This class is responsible for tables outer joins which is already supported in Exposed  when we use table.join()

2020-12-29 16:08 UTC, h-haddad approved these changes

2020-12-31 14:35 UTC, merged