adding selectLookup method under VBlock
kopiLeft/Galite pull request #153
Opened 2020-12-02 15:30 UTC by h-haddad

2020-12-08 08:38 UTC, ZMarouani requested changes

2020-12-08 08:38 UTC, ZMarouani commented on galite-core/src/main/kotlin/org/kopi/galite/form/VBlock.kt
> +        buffer.add(Op.build { col eq field.getSql(recno)!! })
we dont need Op.build

2020-12-08 08:38 UTC, ZMarouani commented on galite-core/src/main/kotlin/org/kopi/galite/form/VBlock.kt
> +        }
you can optimize here by using .single() that will retrieve one element from list or throw exceptions instead

2020-12-08 08:38 UTC, ZMarouani commented on galite-core/src/main/kotlin/org/kopi/galite/form/VField.kt
>  import java.awt.Color
Fix imports order

2020-12-08 13:34 UTC, ZMarouani approved these changes

2020-12-17 13:19 UTC, SNsir requested changes

2020-12-23 08:12 UTC, SNsir approved these changes

2020-12-30 16:19 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/type/Timestamp.kt
> +    val tmp = StringBuffer()
use `buildString`

2020-12-31 13:35 UTC, merged