adding fetchRecord() save() & load() under VBlock
kopiLeft/Galite pull request #160
Opened 2020-12-04 16:29 UTC by h-haddad

2020-12-07 14:50 UTC, ZMarouani requested changes

2020-12-07 14:50 UTC, ZMarouani commented on galite-core/src/main/kotlin/org/kopi/galite/form/VBlock.kt
> +    val query = table.slice(columns).select(condition)
I think we might need to get other conditions from : VBlockDefaultOuterJoin.getFetchRecordCondition(fields)

Also move query inside the transaction block .

2020-12-08 13:55 UTC, ZMarouani approved these changes

2020-12-08 14:43 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/form/VBlock.kt
> +          if (result[columns[1 + idqry]] == 0) {
use `columns[idqry]`

2020-12-08 14:43 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/form/VBlock.kt
> +          fetchBuffer[fetchCount] = result[columns[1 + idqry]] as Int
use `columns[idqry]`

2020-12-08 14:43 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/form/VBlock.kt
> +    transaction {
remove `transaction`

2020-12-08 14:43 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/form/VBlock.kt
> +                fields[i].setQuery_(fetchCount, query, 1 + j)
use `setQuery_(record: Int, query: ResultRow, column: Column<*>)`

2020-12-08 14:43 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/form/VField.kt
> +
remove this

2020-12-08 14:43 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/form/VBlock.kt
> +            field.setQuery_(query, columns[1 + j])
use `setQuery_(query: ResultRow, column: Column<*>)`

2020-12-08 14:43 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/form/VField.kt
> +
remove this method

2020-12-08 14:43 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/form/VBlock.kt
> +    condition.add(VBlockDefaultOuterJoin.getFetchRecordCondition(fields)!!)
Not null assertion here can cause NPE

2020-12-10 15:46 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/form/VBlock.kt
> +    transaction {
no need for transaction in this context

2020-12-10 15:46 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/form/VBlock.kt
> +      }
use single() method, and catch `NoSuchElementException` and `IllegalArgumentException` seperately with corresponding error message

2020-12-10 15:46 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/form/VBlock.kt
> +            for (result in query) {
why you're iterating over query?

2020-12-10 15:46 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/form/VBlock.kt
> +        for (field in fields) {
use `foreach`

2020-12-25 11:41 UTC, hfazai reviewed
comments for load()

2020-12-25 11:41 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/form/VBlock.kt
> +    }
val query = if() ... else ...

2020-12-25 11:41 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/form/VBlock.kt
> +      if (fetchCount < fetchSize) {
have to stop when fetchCount < fetchSize is false

2020-12-25 11:41 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/form/VBlock.kt
> +          }
use foreachIndexed remove `j`

2020-12-25 11:41 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/form/VBlock.kt
> +          }
add empty line after

2020-12-25 12:59 UTC, hfazai reviewed
save()

2020-12-25 12:59 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/form/VBlock.kt
> +              transaction {
no need for transaction in this context

2020-12-25 14:15 UTC, merged