adding serialVersionUID to serializable classes
kopiLeft/Galite pull request #161
Opened 2020-12-07 13:47 UTC by h-haddad

2020-12-08 16:52 UTC, SNsir requested changes

2020-12-08 16:52 UTC, SNsir commented on galite-core/src/main/kotlin/org/kopi/galite/base/ExtendedMessageFormat.kt
> +    private const  val serialVersionUID = 0L
delete space

2020-12-08 16:52 UTC, SNsir commented on galite-core/src/main/kotlin/org/kopi/galite/form/VFieldException.kt
> +    private const  val serialVersionUID = 0L
delete space before val

2020-12-08 16:52 UTC, SNsir commented on galite-core/src/main/kotlin/org/kopi/galite/form/VQueryNoRowException.kt
> +    private const  val serialVersionUID = 0L
delete space before val

2020-12-08 16:52 UTC, SNsir commented on galite-core/src/main/kotlin/org/kopi/galite/form/VQueryOverflowException.kt
> +    private const  val serialVersionUID = 0L
delete space before val

2020-12-08 16:52 UTC, SNsir commented on galite-core/src/main/kotlin/org/kopi/galite/form/VSkipRecordException.kt
> +    private const  val serialVersionUID = 0L
delete space before val

2020-12-08 16:52 UTC, SNsir commented on galite-core/src/main/kotlin/org/kopi/galite/print/PSPrintException.kt
> +    private const  val serialVersionUID = 0L
delete space before val

2020-12-08 16:52 UTC, SNsir commented on galite-core/src/main/kotlin/org/kopi/galite/report/MReport.kt
> +    private const  val serialVersionUID = 0L
delete space before val

2020-12-08 16:52 UTC, SNsir commented on galite-core/src/main/kotlin/org/kopi/galite/report/VBaseRow.kt
> +    private const  val serialVersionUID = 0L
delete space before val

2020-12-08 16:52 UTC, SNsir commented on galite-core/src/main/kotlin/org/kopi/galite/report/VGroupRow.kt
> +    private const  val serialVersionUID = 0L
delete space before val

2020-12-08 16:52 UTC, SNsir commented on galite-core/src/main/kotlin/org/kopi/galite/report/VNoRowException.kt
> +    private const  val serialVersionUID = 0L
delete space before val

2020-12-08 16:52 UTC, SNsir commented on galite-core/src/main/kotlin/org/kopi/galite/util/FaxException.kt
> +    private const  val serialVersionUID = 0L
delete space before val

2020-12-08 16:52 UTC, SNsir commented on galite-core/src/main/kotlin/org/kopi/galite/util/PrintException.kt
> +    private const  val serialVersionUID = 0L
delete space before val

2020-12-08 16:52 UTC, SNsir commented on galite-core/src/main/kotlin/org/kopi/galite/visual/PropertyException.kt
> +    private const  val serialVersionUID = 0L
delete space before val

2020-12-08 16:52 UTC, SNsir commented on galite-core/src/main/kotlin/org/kopi/galite/visual/VExecFailedException.kt
> +    private const  val serialVersionUID = 0L
delete space before val

2020-12-08 16:52 UTC, SNsir commented on galite-core/src/main/kotlin/org/kopi/galite/visual/VInterruptException.kt
> +    private const  val serialVersionUID = 0L
delete space before val

2020-12-08 16:52 UTC, SNsir commented on galite-core/src/main/kotlin/org/kopi/galite/visual/VRuntimeException.kt
> +    private const  val serialVersionUID = 0L
delete space before val

2020-12-08 16:52 UTC, SNsir commented on galite-core/src/main/kotlin/org/kopi/galite/visual/VRuntimeException.kt
> +  }
add 
companion object {
    private const val serialVersionUID = 0L
}
in InconsistencyException class

2020-12-08 16:52 UTC, SNsir commented on galite-core/src/main/kotlin/org/kopi/galite/visual/VRuntimeException.kt
> +  }
add
companion object {
private const val serialVersionUID = 0L
}
in VReportRow class

2020-12-08 16:52 UTC, SNsir commented on galite-core/src/main/kotlin/org/kopi/galite/visual/VExecFailedException.kt
> +    private const  val serialVersionUID = 0L
add
companion object {
private const val serialVersionUID = 0L
}
in VException class

2020-12-09 10:37 UTC, SNsir approved these changes

2020-12-15 16:25 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/list/ObjectFormatter.kt
> +
remove this

2020-12-15 16:25 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/report/ColumnStyle.kt
> +class ColumnStyle : Constants, Serializable {
remove Constants

2020-12-15 16:28 UTC, merged