adding VBlock.getSearchOrder() method
kopiLeft/Galite pull request #162
Opened 2020-12-07 16:08 UTC by h-haddad

2020-12-08 10:35 UTC, ZMarouani requested changes

2020-12-08 14:07 UTC, ZMarouani approved these changes

2020-12-25 13:18 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/form/VBlock.kt
> +  open fun getSearchOrder_():  ArrayList<Pair<Column<*>, SortOrder>> {
return `MutableList` instead of `ArrayList`

2020-12-25 13:18 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/form/VBlock.kt
> +      for (field in fields) {
`forEach`

2020-12-25 13:18 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/form/VBlock.kt
> +          columns.add(field.getColumn(0)!!.column)
missing comment

2020-12-25 13:18 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/form/VBlock.kt
> +          columns.add(field.getColumn(0)!!.column)
why `field.getColumn(0)` ?

2020-12-25 13:18 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/form/VBlock.kt
> +          sizes[j] = sizes[j + 1].also {  sizes[j + 1] = sizes[j]}
This doesn't seems to be right

2020-12-25 13:18 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/form/VBlock.kt
> +    val orderBy = ArrayList<Pair<Column<*>, SortOrder>>(fields.size)
`MutableList`

2020-12-25 15:48 UTC, merged