Implementation of getSuggestions() in VField with Unit tests
kopiLeft/Galite pull request #175
Opened 2020-12-15 09:54 UTC by ZMarouani

2020-12-28 13:59 UTC, h-haddad requested changes

2020-12-28 16:20 UTC, ZMarouani commented on galite-core/src/main/kotlin/org/kopi/galite/form/VBlock.kt
> +    return (triggers[VKT_Type]?.action?.method as? () -> Any)?.invoke()
yes we do

2020-12-28 16:24 UTC, ZMarouani commented on galite-core/src/main/kotlin/org/kopi/galite/form/VField.kt
> -    private set
i'm using setter for test to set the vlist statically  , so i need it to be public

2020-12-28 16:26 UTC, ZMarouani commented on galite-core/src/main/kotlin/org/kopi/galite/list/VListColumn.kt
> +  var title: String?,
need it null , also nullable in kopi

2020-12-29 08:44 UTC, ZMarouani commented on galite-core/src/main/kotlin/org/kopi/galite/list/VList.kt
> +            var autocompleteType: Int,
yes because i'm setting the vList with properties statically in test , because we can't create a list with DSL yet .

2020-12-29 09:02 UTC, ZMarouani commented on galite-tests/src/test/kotlin/org/kopi/galite/tests/form/VFieldTests.kt
> +  companion object{
yes , else the insertion will happen multiple times with every test , using the init of the object prevents that

2020-12-29 09:07 UTC, ZMarouani commented on galite-tests/src/test/kotlin/org/kopi/galite/tests/form/VFieldTests.kt
> +            null)
can't be removed , static data insertion for the test ( can't creat list with dsl yet )

2020-12-29 09:16 UTC, ZMarouani commented on galite-core/src/main/kotlin/org/kopi/galite/form/VListDialog.kt
> +      sizes[i] = max(list[i]!!.width, list[i]!!.title?.length ?: 0)
title is nullable

2020-12-30 09:49 UTC, h-haddad commented on galite-core/src/main/kotlin/org/kopi/galite/form/VField.kt
> -    private set
to check with @hfazai  if we can make this list public

2020-12-30 09:49 UTC, h-haddad commented on galite-core/src/main/kotlin/org/kopi/galite/list/VList.kt
> +            var autocompleteType: Int,
@hfazai to check if we can change it now for make test

2020-12-30 09:53 UTC, h-haddad commented on galite-core/src/main/kotlin/org/kopi/galite/list/VListColumn.kt
> +  var title: String?,
i think that is not null in kopi check it again

2020-12-30 09:54 UTC, h-haddad commented on galite-tests/src/test/kotlin/org/kopi/galite/tests/form/VFieldTests.kt
> +            null)
test work witout it !

2020-12-30 09:55 UTC, h-haddad commented on galite-tests/src/test/kotlin/org/kopi/galite/tests/form/VFieldTests.kt
> +    connectToDatabase()
test work without it

2020-12-30 13:37 UTC, h-haddad requested changes

2021-02-05 15:51 UTC, closed without merging