Add selectFromList() in VField
kopiLeft/Galite pull request #192
Opened 2020-12-23 11:12 UTC by SNsir

2021-01-06 15:05 UTC, h-haddad requested changes

2021-01-07 08:27 UTC, SNsir commented on galite-core/src/main/kotlin/org/kopi/galite/form/VField.kt
> +    return  block!!.executeObjectTrigger(list!!.table) as Table
it is a workaround here , already checked

2021-01-07 08:28 UTC, SNsir commented on galite-core/src/main/kotlin/org/kopi/galite/list/VListColumn.kt
> +  val column_ : Column<*>? = null
already checked with him, everything is fine

2021-01-15 13:34 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/form/VField.kt
> +    val result = displayQueryList(query.toString(), list!!.columns)
`displayQueryList_(query,....)`

2021-01-15 13:34 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/form/VField.kt
> -  @Deprecated("use lookupColumn(corr: Table)")
undo

2021-01-15 13:34 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/form/VField.kt
> -
undo

2021-01-15 13:34 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/form/VField.kt
> -  @Deprecated("use retrieveQuery_(result: ResultRow, column: Column<*>)")
undo

2021-01-15 13:34 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/form/VField.kt
> -  @Deprecated("use setQuery_(record: Int, query: ResultRow, column: Column<*>)")
undo

2021-01-15 13:34 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/form/VField.kt
> -  @Deprecated("use setQuery_(query: ResultRow, column: Column<*>)")
undo

2021-01-15 13:34 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/form/VField.kt
> +import java.sql.SQLException
undo

2021-01-15 13:34 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/form/VField.kt
> -import java.sql.SQLException
undo

2021-01-15 13:59 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/form/VField.kt
> +   */
remove

2021-01-15 14:00 UTC, hfazai approved these changes

2021-01-15 15:05 UTC, h-haddad approved these changes

2021-01-15 15:05 UTC, merged