Implement Notification UI Components
kopiLeft/Galite pull request #215
Opened 2021-01-07 14:34 UTC by SNsir

2021-01-27 11:23 UTC, h-haddad requested changes

2021-01-27 16:17 UTC, SNsir commented on galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/notif/VErrorMessagePopup.kt
> +class VErrorMessagePopup : Popup() {
Maybe we will need it later

2021-01-27 16:17 UTC, SNsir commented on galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/notif/VConfirmNotification.kt
> +    cancel!!.height = "50%"
I used VInputButton like kopi

2021-01-27 16:20 UTC, SNsir commented on galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/notif/VErrorNotification.kt
> +      details = Details("Show details",
this will be fixed later

2021-02-15 13:24 UTC, h-haddad requested changes

2021-02-15 13:24 UTC, h-haddad commented on galite-core/src/main/kotlin/org/kopi/galite/chart/ChartMeasure.kt
>  import java.lang.RuntimeException
reorder

2021-02-15 13:24 UTC, h-haddad commented on galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/notif/VAbstractNotification.kt
>  import com.vaadin.flow.component.Focusable
delete empty line

2021-02-15 13:24 UTC, h-haddad commented on galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/notif/VErrorMessagePopup.kt
>  import org.kopi.galite.ui.vaadin.common.VSpan
add empty lines and put java org then com

2021-02-15 13:24 UTC, h-haddad commented on galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/notif/VErrorNotification.kt
>  import org.kopi.galite.ui.vaadin.base.LocalizedProperties
reorder

2021-02-15 13:24 UTC, h-haddad commented on galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/notif/VInformationNotification.kt
>  import org.kopi.galite.ui.vaadin.base.LocalizedProperties
reorder

2021-02-15 13:24 UTC, h-haddad commented on galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/notif/VWarningNotification.kt
>  import org.kopi.galite.ui.vaadin.base.LocalizedProperties
reorder

2021-02-15 15:04 UTC, h-haddad approved these changes

2021-02-16 09:03 UTC, merged