Form block layout
kopiLeft/Galite pull request #250
Opened 2021-01-31 00:00 UTC by hfazai

2021-02-01 11:12 UTC, SNsir requested changes

2021-02-01 11:12 UTC, SNsir commented on galite-tests/src/test/kotlin/org/kopi/galite/demo/product/ProductForm.kt
> +  override val locale = Locale.FRANCE
already fixed in my PR

2021-02-01 11:12 UTC, SNsir commented on galite-tests/src/test/kotlin/org/kopi/galite/demo/client/ClientForm.kt
> +  override val title = "Clients"
This class is to be fixed in my store application open PR, not here. (already fixed you can review it and merge into master)

2021-02-01 11:12 UTC, SNsir commented on galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/field/Field.kt
> +open class Field(hasIncrement: Boolean, hasDecrement: Boolean) : Div() {
Are you sure about this change?

2021-02-02 00:09 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/block/AbstractBlockLayout.kt
> +
Already exist setVisible() in `Component` class

2021-02-02 12:39 UTC, SNsir approved these changes

2021-02-03 08:29 UTC, merged