Add login page and welcome page CSS
kopiLeft/Galite pull request #256
Opened 2021-02-07 18:28 UTC by SNsir

2021-02-24 12:17 UTC, h-haddad requested changes

2021-02-25 09:01 UTC, SNsir commented on galite-core/src/main/resources/META-INF/resources/frontend/styles/galite/VLoginBox.css
> +}
I couldn't add style when focused

2021-02-25 09:03 UTC, SNsir commented on galite-core/src/main/resources/META-INF/resources/frontend/styles/galite/VHeader.css
> +    height: 63px;
we need margin-left

2021-02-25 09:08 UTC, SNsir commented on galite-core/src/main/resources/META-INF/resources/frontend/styles/galite/VHeader.css
> +#moduleList :not(#user_menu):first-child::part(menu-bar-button):hover {
we will not use the >> icon , and the color is already chosen (gray)

2021-02-25 09:11 UTC, SNsir commented on galite-core/src/main/resources/META-INF/resources/frontend/styles/galite/VHeader.css
> +}
yes we need it

2021-02-25 09:17 UTC, SNsir commented on galite-core/src/main/resources/META-INF/resources/frontend/styles/galite/Form.css
> +}
yes we need it to delete underline

2021-02-25 09:22 UTC, SNsir commented on galite-core/src/main/resources/META-INF/resources/frontend/styles/galite/Form.css
> +
yes it is !

2021-02-25 09:24 UTC, SNsir commented on galite-core/src/main/resources/META-INF/resources/frontend/styles/galite/Report.css
> +}
we need the background color

2021-02-25 16:12 UTC, h-haddad requested changes

2021-02-26 10:56 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/main/MainWindow.kt
> +    welcomeContainer.setId("welcomeContainer")
`welcome-container`

2021-02-26 10:56 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/main/MainWindow.kt
> +    horizontalAlignContainer.setId("horizontalAlignContainer")
`horizontal-align-container`

2021-02-26 16:20 UTC, h-haddad approved these changes

2021-03-01 10:51 UTC, merged