Handling application errors with showing notification dialog
kopiLeft/Galite pull request #270
Opened 2021-02-16 23:34 UTC by hfazai

2021-02-18 15:58 UTC, h-haddad requested changes

2021-02-18 15:58 UTC, h-haddad commented on galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/notif/VAbstractNotification.kt
>     * Sets the notification title.
remove this method setNotificationTitle

2021-02-18 15:58 UTC, h-haddad commented on galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/notif/VConfirmNotification.kt
> +class VConfirmNotification(title: String,
change title to String?

2021-02-18 15:58 UTC, h-haddad commented on galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/notif/VAbstractNotification.kt
> +    super.setFooter(footer)
change to : 
 ```
     super.setHeader(this.title)
    content.add(icon)
    setNotificationMessage(message)
    content.add(this.message)
    super.setContent(content)
    this.setButtons()
    footer.add(buttons)
    super.setFooter(footer)
```

2021-02-18 15:58 UTC, h-haddad commented on galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/notif/VConfirmNotification.kt
> +  private lateinit var cancel: Button
can we initialize those button here instead of doing that in setButtons function?

2021-02-18 15:58 UTC, h-haddad commented on galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/notif/ErrorMessageDetails.kt
> +  private var details = Details()
can we add class : 
`class MoreDetails (summary: String, content: Component): Details(summary, content), Focusable<MoreDetails>`
then in this class : 
`private lateinit var details: MoreDetails`
&
add this code in init 
 ```
if (locale == "fr_FR") {
      details = MoreDetails("Afficher les détails",
                        scroller)
    } else if (locale == "en_GB") {
      details = MoreDetails("Show details",
                        scroller)
    }
    details.addThemeVariants(DetailsVariant.REVERSE, DetailsVariant.FILLED)
    add(details)
```

2021-02-18 15:58 UTC, h-haddad commented on galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/notif/VInformationNotification.kt
> + * @param message the information notification message.
can we add locale in the doc of VInformationNotification, VConfirmNotification, VErrorNotification & VWarningNotification

2021-02-18 15:58 UTC, h-haddad commented on galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/notif/VInformationNotification.kt
> +  private lateinit var close: Button
can we initialize the button here  = Button(LocalizedProperties.getString(locale, "CLOSE"))

2021-02-18 15:58 UTC, h-haddad commented on galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/notif/VWarningNotification.kt
> +  private lateinit var close: Button
can we initialize the button here ! = Button(LocalizedProperties.getString(locale, "CLOSE"))

2021-02-18 15:58 UTC, h-haddad commented on galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/notif/VErrorNotification.kt
> +  private lateinit var close: Button
can we put here `private val close = = Button(LocalizedProperties.getString(locale, "CLOSE"))`

2021-02-18 15:58 UTC, h-haddad commented on galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/visual/DWindow.kt
> +      dialog.addNotificationListener(object : NotificationListener {
empty line

2021-02-18 15:58 UTC, h-haddad commented on galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/visual/DWindow.kt
> +      dialog.addNotificationListener(object : NotificationListener {
empty line

2021-02-18 15:58 UTC, h-haddad commented on galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/visual/DWindow.kt
> +      val dialog = VErrorNotification(VlibProperties.getString("Error"), message!!, notificationLocale)
can you check if we can pass an nullable message here?

2021-02-18 15:58 UTC, h-haddad commented on galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/visual/DWindow.kt
> +      dialog.addNotificationListener(object : NotificationListener {
empty line

2021-02-18 15:58 UTC, h-haddad commented on galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/visual/DWindow.kt
> +      dialog.yesIsDefault = yesIsDefault
empty line

2021-02-18 15:58 UTC, h-haddad commented on galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/visual/VApplication.kt
> +    val dialog = VErrorNotification(VlibProperties.getString("Error"), message!!, notificationLocale)
check nullable message in this case ! 
& add empty line

2021-02-18 15:58 UTC, h-haddad commented on galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/visual/VApplication.kt
>      dialog.addNotificationListener(object : NotificationListener {
add empty line

2021-02-18 15:58 UTC, h-haddad commented on galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/visual/VApplication.kt
> +    dialog.yesIsDefault = yesIsDefault
add empty line

2021-02-18 16:05 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/base/BackgroundThreadHandler.kt
> +   * Excluse access to the UI from a background thread to perform some updates.
Exclusive*

2021-02-18 17:03 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/notif/ErrorMessageDetails.kt
> +    if (locale == "fr_FR") {
`LocalizedProperties.getString()` gets string locale

2021-02-18 17:03 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/notif/ErrorMessageDetails.kt
> +    } else if (locale == "en_GB") {
We will add all locales

2021-02-19 11:10 UTC, h-haddad approved these changes

2021-02-19 17:35 UTC, merged