UI: DWindow implementation
kopiLeft/Galite pull request #277
Opened 2021-02-20 12:40 UTC by hfazai

2021-02-22 13:01 UTC, SNsir requested changes

2021-02-22 15:41 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/wait/WaitWindow.kt
> +    add(image)
added as spinner vaadin icon

2021-02-22 15:42 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/wait/WaitWindow.kt
> +    text.className = Styles.WAIT_WINDOW_TEXT
no need to do that because dialog adds a glass background

2021-02-22 15:42 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/ui/vaadin/wait/WaitWindow.kt
> +  }
no need for now to do that

2021-02-23 11:36 UTC, SNsir approved these changes

2021-02-23 13:00 UTC, merged