adding utils
kopiLeft/Galite pull request #28
Opened 2020-09-15 11:41 UTC by SNsir

2020-09-22 08:21 UTC, SNsir commented on galite-core/src/main/kotlin/org/kopi/galite/util/FaxPrinter.kt
> +        // ----------------------------------------------------------------------
done

2020-09-22 08:21 UTC, SNsir commented on galite-core/src/main/kotlin/org/kopi/galite/util/FaxPrinter.kt
> +// never used locally but must be implemented.
done

2020-09-22 08:21 UTC, SNsir commented on galite-core/src/main/kotlin/org/kopi/galite/util/FaxPrinter.kt
> +
done

2020-09-22 15:33 UTC, ZMarouani requested changes

2020-09-22 15:33 UTC, ZMarouani commented on galite-core/src/main/kotlin/org/kopi/galite/util/Fax.kt
> +  }
Inline it with : 
    = buildString {
      number.filter { it in '0'..'9' }.forEach { append(it) }
    }

2020-09-22 15:33 UTC, ZMarouani commented on galite-core/src/main/kotlin/org/kopi/galite/util/Fax.kt
> +          // ----------------------------------------------------------------------
Delete comment

2020-09-22 15:33 UTC, ZMarouani commented on galite-core/src/main/kotlin/org/kopi/galite/util/Fax.kt
> +    }
Inline function: 
fun readSendQueue(host: String, user: String): Vector<FaxStatus> = readQueue(host, user, "sendq")

2020-09-22 15:33 UTC, ZMarouani commented on galite-core/src/main/kotlin/org/kopi/galite/util/Fax.kt
> +
inline functions

2020-09-22 15:33 UTC, ZMarouani commented on galite-core/src/main/kotlin/org/kopi/galite/util/Fax.kt
> +    private const val DEFAULT_USER = "KOPI" // !!! laurent : why is there a DEFAULT_USER ?
Check or change "kopi" to "Galite" also erase comment

2020-09-22 15:33 UTC, ZMarouani commented on galite-core/src/main/kotlin/org/kopi/galite/util/Fax.kt
> +    }
Delete

2020-09-22 15:33 UTC, ZMarouani commented on galite-core/src/main/kotlin/org/kopi/galite/util/Fax.kt
> +      fax.login(DEFAULT_USER) // !!! laurent 20020626 : why DEFAULT_USER and not user ?
Delete comment ( and similaire comments )

2020-09-22 15:33 UTC, ZMarouani commented on galite-core/src/main/kotlin/org/kopi/galite/util/Fax.kt
> +      fax.login(DEFAULT_USER) // !!! laurent 20020626 : why DEFAULT_USER and not user ?
Delete comment

2020-09-22 15:33 UTC, ZMarouani commented on galite-core/src/main/kotlin/org/kopi/galite/util/Fax.kt
> +                      prozess.nextToken().trim { it <= ' ' },  // STATE (CODE)
Remove ( ) from comment : 
// State of code 
Or it will be considered as commented code in sonarLint

2020-09-22 15:33 UTC, ZMarouani commented on galite-core/src/main/kotlin/org/kopi/galite/util/Fax.kt
> +                      prozess.nextToken().trim { it <= ' ' })) // STATE (TEXT)
Remove ( ) from comment : 
// State text
Or it will be considered as commented code in sonarLint

2020-09-22 15:33 UTC, ZMarouani commented on galite-core/src/main/kotlin/org/kopi/galite/util/PrintJob.kt
> +package org.kopi.galite.util
Add header

2020-09-22 15:33 UTC, ZMarouani commented on galite-core/src/main/kotlin/org/kopi/galite/util/CachePrinter.kt
> +package org.kopi.galite.util
Add header

2020-09-25 10:46 UTC, ZMarouani approved these changes

2020-09-26 23:26 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/util/Fax.kt
> +   */
change this to english

2020-09-26 23:26 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/util/HylaFAXPrinter.kt
> +                     private val attachments: List<*>?) : AbstractPrinter("FaxPrinter $number"), Printer {
fix doc comments

2020-09-26 23:26 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/util/IPPPrinter.kt
> + */
fix doc comments

2020-10-07 17:28 UTC, h-haddad commented on galite-core/src/main/kotlin/org/kopi/galite/util/Fax.kt
> +  private abstract class BasicServ protected constructor(private val debug1: Boolean) : Thread() {
change debug1 to debug

2020-10-07 17:28 UTC, h-haddad commented on galite-core/src/main/kotlin/org/kopi/galite/util/Fax.kt
> +    if (answer == NEEDS_PASSWD) {
can we remove answer and change this to 
  `  if (check(readLine()) == NEEDS_PASSWD) {`

2020-10-07 17:28 UTC, h-haddad commented on galite-core/src/main/kotlin/org/kopi/galite/util/Fax.kt
> +      print("USER $uname\n")
check kopi !! 
`print("PASS 0 \n")`

2020-10-07 17:28 UTC, h-haddad commented on galite-core/src/main/kotlin/org/kopi/galite/util/Fax.kt
> +    print("QUIT" + "\n")
`print("QUIT \n")`

2020-10-07 17:28 UTC, h-haddad commented on galite-core/src/main/kotlin/org/kopi/galite/util/Fax.kt
> +    while (inputStream.read(buffer, 0, 1024).also { read = it } != -1) {
add empty line

2020-10-07 17:28 UTC, h-haddad commented on galite-core/src/main/kotlin/org/kopi/galite/util/Fax.kt
> +    print("TYPE I" + "\n")
remove +

2020-10-07 17:28 UTC, h-haddad commented on galite-core/src/main/kotlin/org/kopi/galite/util/Fax.kt
> +    print("MODE Z" + "\n") // ZIP
remove +

2020-10-07 17:28 UTC, h-haddad commented on galite-core/src/main/kotlin/org/kopi/galite/util/Fax.kt
> +    pstr = makePORT(iaddr, sndsrv.port)
add empty line

2020-10-07 17:28 UTC, h-haddad commented on galite-core/src/main/kotlin/org/kopi/galite/util/Fax.kt
> +    check(line)
add empty line

2020-10-07 17:28 UTC, h-haddad commented on galite-core/src/main/kotlin/org/kopi/galite/util/Fax.kt
> +    st.nextToken()
add empty line

2020-10-07 17:28 UTC, h-haddad commented on galite-core/src/main/kotlin/org/kopi/galite/util/Fax.kt
> +    check(readLine())
add empty line

2020-10-07 17:28 UTC, h-haddad commented on galite-core/src/main/kotlin/org/kopi/galite/util/Fax.kt
> +    pstr = makePORT(iaddr, recsrv.port)
add empty line

2020-10-07 17:28 UTC, h-haddad commented on galite-core/src/main/kotlin/org/kopi/galite/util/Fax.kt
> +    pstr = makePORT(iaddr, recsrv.port)
add empty line

2020-10-07 17:28 UTC, h-haddad commented on galite-core/src/main/kotlin/org/kopi/galite/util/Fax.kt
> +    print(what + "\n")
add empty line and remove +

2020-10-07 17:28 UTC, h-haddad commented on galite-core/src/main/kotlin/org/kopi/galite/util/Fax.kt
> +    Utils.log("Fax", "NEW JOB:$id / user: $user")
add empty line

2020-10-07 17:28 UTC, h-haddad commented on galite-core/src/main/kotlin/org/kopi/galite/util/Fax.kt
> +    command("JPARM PAGECHOP \"default\"")
correct to remove \

2020-10-07 17:28 UTC, h-haddad commented on galite-core/src/main/kotlin/org/kopi/galite/util/Fax.kt
> +  }
to check in kopi

2020-10-07 17:28 UTC, h-haddad commented on galite-core/src/main/kotlin/org/kopi/galite/util/Fax.kt
> +    return ((0xff and iaddr[0].toInt()).toString() + "," + (0xff and iaddr[1].toInt()) + "," +
add empty line

2020-10-07 17:28 UTC, h-haddad commented on galite-core/src/main/kotlin/org/kopi/galite/util/Fax.kt
> +    if (str == null) {
add empty line

2020-10-07 17:28 UTC, h-haddad commented on galite-core/src/main/kotlin/org/kopi/galite/util/Fax.kt
> +    }
to check

2020-10-07 17:28 UTC, h-haddad commented on galite-core/src/main/kotlin/org/kopi/galite/util/Fax.kt
> +  val host: String
remove them

2020-10-07 17:28 UTC, h-haddad commented on galite-core/src/main/kotlin/org/kopi/galite/util/Fax.kt
> +    override val message: String = super.message.toString() + " Replay Code: " + number
can we change it to function getMessage()

2020-10-07 17:28 UTC, h-haddad commented on galite-core/src/main/kotlin/org/kopi/galite/util/Fax.kt
> +    protected fun debug(message: String?) {
String remove ?

2020-10-07 17:28 UTC, h-haddad commented on galite-core/src/main/kotlin/org/kopi/galite/util/Fax.kt
> +      // ----------------------------------------------------------------------
remove

2020-10-07 17:28 UTC, h-haddad commented on galite-core/src/main/kotlin/org/kopi/galite/util/Fax.kt
> +      try {
add empty line

2020-10-07 17:28 UTC, h-haddad commented on galite-core/src/main/kotlin/org/kopi/galite/util/Fax.kt
> +        debug("RecvServ.run: Erzeuge InputStream")
add empty line

2020-10-07 17:28 UTC, h-haddad commented on galite-core/src/main/kotlin/org/kopi/galite/util/Fax.kt
> +        while (dataInputStream.read(buf).also { anz = it } > 0) {
add empty line

2020-10-07 17:28 UTC, h-haddad commented on galite-core/src/main/kotlin/org/kopi/galite/util/Fax.kt
> +      try {
add empty line

2020-10-07 17:28 UTC, h-haddad commented on galite-core/src/main/kotlin/org/kopi/galite/util/Fax.kt
> +        debug("SendServ.run: Create OutputStream")
add empty line

2020-10-08 10:36 UTC, closed without merging