Implement Forms and reports Style in CSS
kopiLeft/Galite pull request #302
Opened 2021-03-30 07:25 UTC by SNsir

2021-04-08 11:18 UTC, h-haddad requested changes

2021-04-08 11:18 UTC, h-haddad commented on galite-core/src/main/resources/META-INF/resources/frontend/styles/galite/Report.css
> +}
add empty line

2021-04-08 11:18 UTC, h-haddad commented on galite-core/src/main/resources/META-INF/resources/frontend/styles/galite/Report.css
> +     padding-left: 9px;
add color here : color: #505050;

2021-04-08 11:18 UTC, h-haddad commented on galite-core/src/main/resources/META-INF/resources/frontend/styles/galite/Report.css
> +}
remove this

2021-04-09 11:18 UTC, h-haddad approved these changes

2021-04-09 11:18 UTC, hfazai approved these changes

2021-04-09 11:19 UTC, merged