adding visual classes
kopiLeft/Galite pull request #33
Opened 2020-09-18 16:21 UTC by SNsir

2020-09-23 09:49 UTC, ZMarouani requested changes

2020-09-23 09:49 UTC, ZMarouani commented on galite-core/src/main/kotlin/org/kopi/galite/visual/ApplicationConfiguration.kt
> +  abstract val informationText: String
Change to abstract methods instead of abstract fields ( check other fields too )

2020-09-23 09:49 UTC, ZMarouani commented on galite-core/src/main/kotlin/org/kopi/galite/visual/ApplicationContext.kt
> +  abstract val isWebApplicationContext: Boolean
Change to abstract methods ( check other abstract val/r too )

2020-09-23 09:49 UTC, ZMarouani commented on galite-core/src/main/kotlin/org/kopi/galite/visual/ApplicationContext.kt
> +          System.err.println("ERROR: No application configuration available")
Use when instead of if 
Use versionArray.forEach{ instead of for (i in ...indices )

2020-09-25 11:19 UTC, ZMarouani approved these changes

2020-09-27 21:42 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/visual/ApplicationContext.kt
> +              "galite@kopileft.com" //TODO
change it to
TODO()

2020-09-27 21:42 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/visual/ApplicationContext.kt
> +              "fehler@kopileft.com" //TODO
change it to 
              TODO()

2020-09-27 21:42 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/visual/ApplicationContext.kt
> +              writer.println("User-IP:             " + applicationContext.getApplication().getUserIP())
change it to
TODO()

2020-09-27 21:42 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/visual/ApplicationContext.kt
> +              writer.println("Galite-User:           " + applicationContext.getApplication().getUserName())
change it to
TODO()

2020-09-27 21:42 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/visual/ApplicationContext.kt
> +    fun getDefaults(): ApplicationConfiguration? = applicationContext.getApplication().getApplicationConfiguration()
fun getDefaults(): ApplicationConfiguration = applicationContext.getApplication().getApplicationConfiguration()

and please fix all null checks for ApplicationConfiguration and all other variables

2020-09-27 21:42 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/visual/ApplicationContext.kt
> +                      reason: Throwable?) {
reason: Throwable

and fix all null checks

2020-09-27 21:42 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/util/PrintJob.kt
> +  var numberOfPages: Int
var numberOfPages: Int = -1

2020-09-27 21:42 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/util/PrintJob.kt
> +    numberOfPages = -1
remove this as it is initialized

2020-09-27 21:42 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/util/Printer.kt
>  interface Printer {
add docs
/**
 * An interface that defines printer devices
 *
 * Such printers may be remote printers, local printers, print-to-file, fax
 * mailer or whatever
 */

2020-09-27 21:42 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/util/Printer.kt
> +import java.awt.PrintJob
this make you user java.awt.PrintJob instead of galite one
remove this please.

2020-09-29 10:43 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/base/Utils.kt
> + * To load default images (that appear in that appear in resources/org/kopi/galite)
fix this comment

2020-09-29 10:43 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/visual/ApplicationContext.kt
> -          }
keep this for now

2020-09-29 10:43 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/visual/ApplicationContext.kt
> -              writer.println("Galite-User:           " + applicationContext.getApplication().getUserName())
User-Name

2020-09-29 10:43 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/visual/ApplicationContext.kt
> +            failureID = run {
why run ?

2020-09-29 10:43 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/visual/ApplicationContext.kt
> -              " " // no information
why did you remove this

2020-09-29 10:47 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/visual/ApplicationContext.kt
> +        else -> {
you still using when statement whereas you have two conditions: Can simply done with if..else statement

2020-09-29 10:51 UTC, SNsir commented on galite-core/src/main/kotlin/org/kopi/galite/visual/ApplicationContext.kt
> -              writer.println("Galite-User:           " + applicationContext.getApplication().getUserName())
already Fixed

2020-09-29 11:17 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/visual/ApplicationContext.kt
> +          }
````KOTLIN
failureID = try {
....

2020-09-29 11:17 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/visual/ApplicationContext.kt
> +          } catch (e: PropertyException) {
why you're using .toString()

2020-09-29 11:38 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/visual/ApplicationContext.kt
>            }
I think that sender is not nullable but getStringFor("debugging.mail.sender") couldn't return nullable value

2020-09-29 14:03 UTC, hfazai approved these changes

2020-09-29 15:14 UTC, merged