VaadinUI: Waiting progress bar
kopiLeft/Galite pull request #343
Opened 2021-05-19 00:34 UTC by hfazai

2021-05-19 13:48 UTC, h-haddad requested changes

2021-05-19 13:48 UTC, h-haddad commented on galite-core/src/main/resources/META-INF/resources/frontend/styles/galite/progress.css
> +/*
typo : file name > **P**rogress.css

2021-05-20 08:18 UTC, hfazai commented on galite-core/src/main/resources/META-INF/resources/frontend/styles/galite/progress.css
> +/*
css files should be in lowercase

2021-05-25 07:56 UTC, h-haddad approved these changes

2021-05-31 11:33 UTC, merged