adding visual preview window
kopiLeft/Galite pull request #45
Opened 2020-09-27 14:26 UTC by hfazai

2020-09-30 15:58 UTC, ZMarouani requested changes

2020-09-30 15:58 UTC, ZMarouani commented on galite-core/src/main/kotlin/org/kopi/galite/visual/VWindow.kt
>        i -= 2
Change while loops to for Loops for a better readability

2020-09-30 15:58 UTC, ZMarouani commented on galite-core/src/main/kotlin/org/kopi/galite/visual/VWindow.kt
>          var value = (listeners[i + 1] as MessageListener).ask(message, yesIsDefault)
Change while to for loop

2020-09-30 15:58 UTC, ZMarouani commented on galite-core/src/main/kotlin/org/kopi/galite/preview/VPreviewWindow.kt
> +    printFile = printJob.dataFile
In printJob it's var datafile , so we need to change this one or change in printJob

2020-09-30 15:58 UTC, ZMarouani commented on galite-core/src/main/kotlin/org/kopi/galite/preview/VPreviewWindow.kt
> +  private var imageFile: String? = null
Verify nullability ( there are no != null conditions on them in kopi )

2020-09-30 15:58 UTC, ZMarouani commented on galite-core/src/main/kotlin/org/kopi/galite/preview/VPreviewWindow.kt
> +  private var imageFile: String? = null
Not nullable

2020-09-30 15:58 UTC, ZMarouani commented on galite-core/src/main/kotlin/org/kopi/galite/preview/VPreviewWindow.kt
> +  override fun getTitle(): String? {
not nullable

2020-10-05 11:53 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/visual/VWindow.kt
>    private var actors: ArrayList<VActor> = arrayListOf()
actors is gonna be intialized anyway so i think it's better to leave it not nullable

2020-10-05 12:01 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/visual/VWindow.kt
>          when (value) {
for better visibility I think we better keep it as it is

2020-10-05 12:19 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/visual/VWindow.kt
> +    // TODO set it abstract
I kept it as it is in kopi. I also mark it //TODO
when we finsh model we'll see what we can do for it

2020-10-08 11:17 UTC, ZMarouani approved these changes

2020-10-08 15:24 UTC, merged