Galite v45
kopiLeft/Galite pull request #46
Opened 2020-09-28 10:51 UTC by SNsir

2020-09-30 09:35 UTC, ZMarouani requested changes

2020-09-30 09:35 UTC, ZMarouani commented on galite-core/src/main/kotlin/org/kopi/galite/visual/VCommand.kt
> +  open fun setEnabled(enabled: Boolean) {
Check if it needs "open "

2020-09-30 09:35 UTC, ZMarouani commented on galite-core/src/main/kotlin/org/kopi/galite/visual/VCommand.kt
> +  open fun helpOnCommand(help: VHelpGenerator) {
Check if it needs open

2020-10-01 14:41 UTC, SNsir commented on galite-core/src/main/kotlin/org/kopi/galite/visual/VModel.kt
>  import java.io.Serializable
this class is not mine, ignore it

2020-10-01 14:41 UTC, SNsir commented on galite-core/src/main/kotlin/org/kopi/galite/visual/VModel.kt
> +  abstract fun getActorIdent(): String
ignore it

2020-10-01 14:52 UTC, SNsir commented on galite-core/src/main/kotlin/org/kopi/galite/visual/VCommand.kt
> +  open fun setEnabled(enabled: Boolean) {
not mine ignore it

2020-10-01 14:52 UTC, SNsir commented on galite-core/src/main/kotlin/org/kopi/galite/visual/VCommand.kt
> +  open fun helpOnCommand(help: VHelpGenerator) {
ignore it

2020-10-14 10:40 UTC, ZMarouani requested changes

2020-10-14 10:40 UTC, ZMarouani commented on galite-core/src/main/kotlin/org/kopi/galite/preview/VPreviewWindow.kt
> +}
Add empty line at the end of file

2020-10-14 10:40 UTC, ZMarouani commented on galite-core/src/main/kotlin/org/kopi/galite/visual/VlibProperties.kt
>  import org.kopi.galite.util.base.InconsistencyException
Add empty space between

2020-10-14 10:49 UTC, ZMarouani approved these changes

2020-10-15 14:39 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/chart/VChartType.kt
> +import org.kopi.galite.report.VReportCommand
remove unused inport

2020-10-15 14:39 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/print/DefaultPrintManager.kt
> +      throw VExecFailedException(exc.message!!)
remove (!!) it can accept nullable

2020-10-15 14:39 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/print/DefaultPrintManager.kt
> + }
indentation

2020-10-15 14:39 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/report/VReportCommand.kt
> +  override fun performAction(action: Action, block: Boolean) {
add :
`@Deprecated("use method performAsyncAction", ReplaceWith("performAsyncAction(action, block)"))`

2020-10-15 14:39 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/report/VReportCommand.kt
> +                report as Printable,
remove `as Printable` since `VReport` is a `Printable`
then you can remove unused import

2020-10-15 14:39 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/report/VReportCommand.kt
> +                null)
fix indentation

2020-10-15 14:39 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/visual/ApplicationConfiguration.kt
> +        ApplicationContext.applicationContext!!.getApplication()?.getApplicationConfiguration()
undo

2020-10-15 14:39 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/visual/ApplicationConfiguration.kt
> +        ApplicationContext.applicationContext!!.getApplication()?.setApplicationConfiguration(conf)
undo

2020-10-15 14:39 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/visual/ApplicationContext.kt
> -
undo

2020-10-15 14:39 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/visual/VActor.kt
> +              || (iconName != null
undo

2020-10-15 14:39 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/visual/VActor.kt
> +            this.help)
undo

2020-10-15 14:39 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/visual/VWindow.kt
> +}
undo

2020-10-15 14:39 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/visual/VlibProperties.kt
> +              e.message!!,
remove (!!) 

"org.kopi.galite.visual.VlibProperties.getString(key: String, params: Any?)"

2020-10-15 15:09 UTC, merged