Unit Tests : adding tests for VDimension, VMeasure, Domain, ExtendedChoiceFormat and getSearchTable
kopiLeft/Galite pull request #495
Opened 2021-11-09 10:22 UTC by MedAliMarz

This PR adds unit tasks for the classes:
- VDimension
- VMeasure
- Domain
- ExtendedChoiceFormat

and for the function: getSearchTable (with corner cases)

2021-11-11 14:08 UTC, h-haddad commented on galite-tests/src/test/kotlin/org/kopi/galite/tests/form/FormWithNullableColumnTest.kt
> +  fun InnerLeftInnerJoinFourTables() {
typo : *inner

2021-11-11 14:08 UTC, h-haddad commented on galite-tests/src/test/kotlin/org/kopi/galite/tests/form/FormWithNullableColumnTest.kt
> +  fun InnerJoinNoJoinTwoTables() {
typo : *inner

2021-11-11 14:12 UTC, h-haddad commented on galite-tests/src/test/kotlin/org/kopi/galite/tests/form/FormWithNullableColumnTest.kt
> +  fun NoJoinInnerJoinTwoTables() {
typo : *noJoin

2021-11-11 14:12 UTC, h-haddad commented on galite-tests/src/test/kotlin/org/kopi/galite/tests/form/FormWithNullableColumnTest.kt
> +  fun LeftJoinNoJoinTwoTables() {
typo : *leftJoin

2021-11-11 14:13 UTC, h-haddad commented on galite-tests/src/test/kotlin/org/kopi/galite/tests/form/FormWithNullableColumns.kt
> +        println("-----------Generating list-----------------")
delete all println

2021-11-11 14:21 UTC, h-haddad commented on galite-tests/src/test/kotlin/org/kopi/galite/tests/form/FormWithNullableColumns.kt
> +    columns(o.client_id)
when you put all field as skipped you can't access to this block

2021-11-12 07:50 UTC, MedAliMarz commented on galite-tests/src/test/kotlin/org/kopi/galite/tests/base/ExtendedChoiceFormatTests.kt
> +        assertEquals("zero", extendedChoiceFormat.format(0.0))
Done

2021-11-12 16:04 UTC, h-haddad requested changes

2021-11-15 08:10 UTC, MedAliMarz commented on galite-tests/src/test/kotlin/org/kopi/galite/tests/chart/VMeasureTests.kt
>  class VMeasureTests {
As we are testing the VMeasure class, we don't have any functionalities to verify, therefore we check if the attributes are passed correctly to the internal model

2021-11-15 08:12 UTC, MedAliMarz commented on galite-tests/src/test/kotlin/org/kopi/galite/tests/chart/VMeasureTests.kt
> +  }
Done

2021-11-17 15:04 UTC, h-haddad approved these changes

2021-11-23 14:27 UTC, hfazai approved these changes

2021-11-23 14:27 UTC, merged