Add UI Tests for Block, Form, Report and List
kopiLeft/Galite pull request #503
Opened 2021-11-22 16:44 UTC by MedAliMarz

This PR adds missing UI tests for:
- Block
- Form
- Report
- List

2021-11-24 10:16 UTC, h-haddad requested changes

2021-11-24 10:16 UTC, h-haddad commented on galite-tests/src/test/kotlin/org/kopi/galite/tests/ui/vaadin/report/ReportTests.kt
> +    assertTrue(anchor.href.contains(simpleReport.title))
you can assert also on` div with class='download-file-title' `end with CSV (add it to pdf, xls and xlsx tests)

2021-11-24 10:16 UTC, h-haddad commented on galite-tests/src/test/kotlin/org/kopi/galite/tests/ui/vaadin/report/ReportTests.kt
> +    formWithReport.open()
remove this part from your tests and add : 
```
@Before
  fun `login to the App`() {
    login()
    formWithReport.open()
  }
```

2021-11-24 10:16 UTC, h-haddad commented on galite-tests/src/test/kotlin/org/kopi/galite/tests/ui/vaadin/report/ReportTests.kt
> +    // Trigger the command and check that the downloaderDialog is opened
put comment before triggerCommand()

2021-11-24 10:16 UTC, h-haddad commented on galite-tests/src/test/kotlin/org/kopi/galite/tests/examples/TestFieldsForm.kt
> +    command(item = query){
add space before braces, (also for update and insert)

2021-11-24 10:16 UTC, h-haddad commented on galite-tests/src/test/kotlin/org/kopi/galite/tests/ui/vaadin/list/ListTests.kt
> +    formWithList.open()
add : 
 ```
@Before
  fun `login to the App`() {
    login()
    formWithList.open()
  }
```

2021-11-24 10:16 UTC, h-haddad commented on galite-tests/src/test/kotlin/org/kopi/galite/tests/ui/vaadin/report/ReportTests.kt
> +    // Trigger the command and check that the downloaderDialog is opened
reverse

2021-11-24 10:16 UTC, h-haddad commented on galite-tests/src/test/kotlin/org/kopi/galite/tests/ui/vaadin/report/ReportTests.kt
> +    // Trigger the command and check that the downloaderDialog is opened
reverse

2021-11-24 11:14 UTC, MedAliMarz commented on galite-tests/src/test/kotlin/org/kopi/galite/tests/ui/vaadin/block/SimpleBlockTests.kt
> +    assertEquals(VConstants.ACS_SKIPPED, block.visitFieldToSkippedField.access[Mode.INSERT.value])
I think that will be needed if the access array is unaccessible, @hfazai what do you think, do we add the getter? or directly use the access array?

2021-11-24 11:30 UTC, MedAliMarz commented on galite-tests/src/test/kotlin/org/kopi/galite/tests/ui/vaadin/block/SimpleBlockTests.kt
> +    assertEquals(VConstants.ACS_MUSTFILL, block.skippedToMustFillField.access[Mode.INSERT.value])
Added it only for the update button, but not for the query button as the fields access didn't change (even after adding onQueryX, where X is the original field access)

2021-11-24 12:22 UTC, MedAliMarz commented on galite-tests/src/test/kotlin/org/kopi/galite/tests/ui/vaadin/form/MultipleBlockFormTests.kt
> +  fun `test the shortcut help button`() {
Changed it to `test the actors shortcut dialog`.

2021-11-24 12:41 UTC, MedAliMarz commented on galite-tests/src/test/kotlin/org/kopi/galite/tests/ui/vaadin/form/MultipleBlockFormTests.kt
> +    windowsItems = windowsContainer._find<VWindowsMenuItem> { classes = "item" }
The windows Container and Items stays the same (same element in the dom) also the `windowsItems[1].click()` is simulating the click even if the `EnhanceDialog` is hidden

2021-11-24 12:46 UTC, MedAliMarz commented on galite-tests/src/test/kotlin/org/kopi/galite/tests/ui/vaadin/list/ListTests.kt
> +  fun `test list command with sorted rows`() {
Yes, but it should exist, to have a corresponding behavior to Kopi, marked as ignored for now!

2021-11-24 13:56 UTC, MedAliMarz commented on galite-tests/src/test/kotlin/org/kopi/galite/tests/ui/vaadin/form/MultipleBlockFormTests.kt
> +    assertEquals(10, navigationColumns[1].children.count())
Done for both, thanks for the suggestion

2021-12-07 14:57 UTC, h-haddad requested changes

2021-12-07 14:57 UTC, h-haddad commented on galite-tests/src/test/kotlin/org/kopi/galite/tests/examples/TestFieldsVisibilityForm.kt
> +  runForm(formName = TestFieldsForm())
change to TestFieldsVisibilityForm

2021-12-07 14:57 UTC, h-haddad commented on galite-tests/src/test/kotlin/org/kopi/galite/tests/examples/TestFieldsVisibilityForm.kt
> +  }
unused

2021-12-07 14:57 UTC, h-haddad commented on galite-tests/src/test/kotlin/org/kopi/galite/tests/examples/TestFieldsVisibilityForm.kt
> +  }
unused

2021-12-07 14:57 UTC, h-haddad commented on galite-tests/src/test/kotlin/org/kopi/galite/tests/examples/TestFieldsVisibilityForm.kt
> +  }
unused

2021-12-07 14:57 UTC, h-haddad commented on galite-tests/src/test/kotlin/org/kopi/galite/tests/ui/vaadin/list/ListTests.kt
> +import org.junit.Ignore
reorder

2021-12-07 14:57 UTC, h-haddad commented on galite-tests/src/test/kotlin/org/kopi/galite/tests/ui/vaadin/report/ReportTests.kt
> +import org.kopi.galite.testing.waitAndRunUIQueue
reorder

2021-12-07 14:57 UTC, h-haddad commented on galite-tests/src/test/kotlin/org/kopi/galite/tests/ui/vaadin/report/ReportTests.kt
>    fun `test export CSV`() {
check if test export XLSX, test export XLS, test export CSV, test export PDF stay valid after merge with master

2021-12-16 09:19 UTC, hfazai approved these changes

2021-12-16 10:25 UTC, merged