implement VFixnumField
kopiLeft/Galite pull request #51
Opened 2020-10-02 16:12 UTC by SNsir

2020-10-06 14:54 UTC, ZMarouani requested changes

2020-10-06 14:54 UTC, ZMarouani commented on galite-core/src/main/kotlin/org/kopi/galite/form/VFixnumField.kt
> +    var dot: Int
val dot

2020-10-06 14:54 UTC, ZMarouani commented on galite-core/src/main/kotlin/org/kopi/galite/form/VFixnumField.kt
> +    if ((str.indexOf(',').also { dot = it }) == -1) {
Add empty line before if

2020-10-06 14:54 UTC, ZMarouani commented on galite-core/src/main/kotlin/org/kopi/galite/form/VFixnumField.kt
> +    when {
empty line between

2020-10-06 14:54 UTC, ZMarouani commented on galite-core/src/main/kotlin/org/kopi/galite/form/VFixnumField.kt
> +      }
Remove {} : 
... -> return ..

2020-10-06 14:54 UTC, ZMarouani commented on galite-core/src/main/kotlin/org/kopi/galite/form/VFixnumField.kt
> +        }
Refactor to : 
return when (precomma) {
          "0" -> "$num/$den"
          "-0" -> "-$num/$den"
          else -> "$precomma $num/$den"
        }

2020-10-06 14:54 UTC, ZMarouani commented on galite-core/src/main/kotlin/org/kopi/galite/form/VFixnumField.kt
> +      }
Refactor to : 
if (value[0] != null 
          && (criticalMinValue != null 
          && value[0]!! < criticalMinValue!! || criticalMaxValue != null 
                                                && value[0]!! > criticalMaxValue!!)) {
        setHasCriticalValue(true)
        return
      }

2020-10-06 14:54 UTC, ZMarouani commented on galite-core/src/main/kotlin/org/kopi/galite/form/VField.kt
> +  open fun getDisplay(): UField {
Return type is "UField?"

2020-10-06 14:54 UTC, ZMarouani commented on galite-core/src/main/kotlin/org/kopi/galite/form/VFixnumField.kt
> +    }
Change to : 
getDisplay()?.let { (it as UTextField).setHasCriticalValue(critical) }

2020-10-06 14:54 UTC, ZMarouani commented on galite-core/src/main/kotlin/org/kopi/galite/form/VFixnumField.kt
> +  /*
Delete comment

2020-10-06 14:54 UTC, ZMarouani commented on galite-core/src/main/kotlin/org/kopi/galite/form/VFixnumField.kt
> +          : Boolean
Fix comment position

2020-10-06 14:54 UTC, ZMarouani commented on galite-core/src/main/kotlin/org/kopi/galite/form/VFixnumField.kt
> +   */
Delete comment

2020-10-06 14:54 UTC, ZMarouani commented on galite-core/src/main/kotlin/org/kopi/galite/form/VFixnumField.kt
> +                   var maxval: Fixed?)
private val digits: Int,
private var maxScale: Int,
val fraction: Boolean,
var minval: Fixed?,
var maxval: Fixed?

2020-10-06 14:54 UTC, ZMarouani commented on galite-core/src/main/kotlin/org/kopi/galite/form/VFixnumField.kt
> +    this.fraction = fraction
We dont need to add this.property = arg when the property is already declared as val or var in the constructor

2020-10-06 14:54 UTC, ZMarouani commented on galite-core/src/main/kotlin/org/kopi/galite/form/VFixnumField.kt
> +    this.maxScale = maxScale
Delete

2020-10-06 14:54 UTC, ZMarouani commented on galite-core/src/main/kotlin/org/kopi/galite/form/VFixnumField.kt
> +   * ----------------------------------------------------------------------
Delete

2020-10-06 14:54 UTC, ZMarouani commented on galite-core/src/main/kotlin/org/kopi/galite/form/VFixnumField.kt
> +     * Calculaes the upper bound of a fixnum field : FIXNUM(digits, scale)
Calculates

2020-10-06 14:54 UTC, ZMarouani commented on galite-core/src/main/kotlin/org/kopi/galite/visual/VlibProperties.kt
> +  fun getString(key: String, arrayOf: Array<Any>): String {
I think it needs to be Array<Any?>

2020-10-07 11:21 UTC, SNsir commented on galite-core/src/main/kotlin/org/kopi/galite/visual/VlibProperties.kt
> +  fun getString(key: String, arrayOf: Array<Any>): String {
ignore it

2020-10-07 11:24 UTC, SNsir commented on galite-core/src/main/kotlin/org/kopi/galite/form/VFixnumField.kt
> +    if (v != null && (v is Int)) {
it is an overriden method, can't be nullable

2020-10-08 10:29 UTC, ZMarouani approved these changes

2020-10-14 13:52 UTC, h-haddad commented on galite-core/src/main/kotlin/org/kopi/galite/form/VFixnumField.kt
> +    if (scale > maxScale) {
maxScale --> fieldMaxScale 

then in  fun setScale(record: Int, scale: Int) { --> change fieldMaxScale to maxScale

2020-10-14 15:07 UTC, h-haddad approved these changes

2020-10-15 23:26 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/form/VFixnumField.kt
> +  // dynamic data
move this just before `minval`

2020-10-15 23:26 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/form/VFixnumField.kt
> +                                                           fieldMaxScale))
fieldMaxScale.toString()

2020-10-15 23:26 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/form/VFixnumField.kt
> +      throw InconsistencyException(MessageCode.getMessage("VIS-00060", scale, maxScale))
scale.toString(), maxScale.toString()

2020-10-15 23:26 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/form/VFixnumField.kt
> +          throw VFieldException(this, MessageCode.getMessage("VIS-00011", arrayOf<Any>(scale) as Array<Any>?))
arrayOf(scale)

2020-10-15 23:26 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/form/VFixnumField.kt
> +          throw VFieldException(this, MessageCode.getMessage("VIS-00012", arrayOf<Any>(minval!!) as Array<Any>?))
arrayOf(minVal)

2020-10-15 23:26 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/form/VFixnumField.kt
> +          throw VFieldException(this, MessageCode.getMessage("VIS-00009", arrayOf<Any>(maxval!!) as Array<Any>?))
arrayOf(maxVal)

2020-10-15 23:26 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/form/VFixnumField.kt
> +          = computeSum(exclude)?.let { computeSum(exclude) as NotNullFixed } ?: coalesceValue
code style : move '=' to the previous line
`as?`

2020-10-16 16:21 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/form/VFixnumField.kt
> +          throw VFieldException(this, MessageCode.getMessage("VIS-00011", arrayOf(scale) as Array<Any>?))
remove ` as Array<Any>?`

2020-10-16 16:21 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/form/VFixnumField.kt
> +        if (toText(v.setScale(maxScale)).length > width) {
remove ` as Array<Any>?`

2020-11-03 21:40 UTC, merged