Upgrade Vaadin version from 22.0.14 to 23.3.8
kopiLeft/Galite pull request #601
Opened 2023-08-17 09:40 UTC by MedAzizTousli

### Main changes:

- Change the following versions:
  - `Java` from 8 to 11
  - `Vaadin` from 22.0.14 to 23.3.8
  - `Karibu Testing` from 1.3.3 to 1.3.23
  - `Enhanced Dialog` from 21.0.0 to 23.1.2
  - `Springboot` from 2.4.0 to 2.7.14
- Implement `Javax Activation` in Gradle
- Correct `TestingLifecycleHook` interface
- Correct `WaitWindow` class
- Clean `Node Modules` residue to make `Vite.js` work
- Ignore failing unit tests due to `Karibu Testing` (Look up issue [here](https://github.com/mvysny/karibu-testing/issues/156))

_Attached is a PDF document (written in French) that contains the above changes in detail._  
[dossierMigration.pdf](https://github.com/kopiLeft/Galite/files/12367736/dossierMigration.pdf)

2023-08-17 17:02 UTC, RiadhCherni approved these changes

2023-08-18 15:24 UTC, mgrati requested changes

2023-08-18 15:24 UTC, mgrati commented on .github/workflows/gradle.yml
> +        java: [ 11 ]
It is also interesting to check the compatibility of Galite with java 17.

2023-08-18 15:24 UTC, mgrati commented on galite-core/src/main/kotlin/org/kopi/galite/visual/ui/vaadin/common/Dialog.kt
> -@NpmPackage(value = "@vaadin-component-factory/vcf-enhanced-dialog", version = "22.0.6")
In Galite, we use the add on vcf-enhanced-dialog for fields containing rich text. 
We need to test this function to make sure that these changes do not affect the current state.
You can create a string field with the parameter styled = true to check theses changes. 
(Example in galite-demo, field  informations of TaxRuleForm)

2023-08-18 16:48 UTC, mgrati approved these changes

2023-08-18 16:56 UTC, merged