Fix table's sequence fetching when inserting new record
kopiLeft/Galite pull request #604
Opened 2023-09-06 15:06 UTC by achraf-debug

in this pull request i fixed the  table's sequence fetching when inserting new record. I also fixed a bug of ClassCastException of LocalDateTime to Instant in CallendarBlock. I tested the fetch of sequence of the base table.

2023-11-23 15:21 UTC, RiadhCherni requested changes

2023-11-23 15:37 UTC, mgrati commented on galite-core/src/main/kotlin/org/kopi/galite/visual/ui/vaadin/calendar/DAbstractFullCalendar.kt
Je ne suis pas d'accord pour la suppression de cette modification. C'est une modification pour résoudre un problème trouvé lors du test, et qui est aussi décrite dans la description du pull request.

2023-11-23 15:41 UTC, mgrati commented on galite-data/src/main/kotlin/org/kopi/galite/database/Connection.kt
J'ai ajouté l'appel de databaseConfig dans galite-test pour initialiser le SQL Logger, Donc j'ai initialisé le paramètre schema par null pour un appel plus propre de la méthode (ne pas avoir besoin d'appeler databaseConfig(null)).

2023-11-23 15:44 UTC, mgrati commented on galite-data/src/main/kotlin/org/kopi/galite/database/Utils.kt
Quelle séquence de DBSchema? Il n'y a aucune liaison entre les séquences définies dans un DBSchema et le champ qui est incrémenté par cette séquence.

2023-11-23 15:47 UTC, mgrati commented on galite-demo/galite-vaadin/src/main/kotlin/org/kopi/galite/demo/client/ClientForm.kt
Merci de détailler les erreurs que tu as rencontré car je peux : 
- Ajouter et sauvegarder des nouveaux clients
- Ajouter des ventes à un client existant et sauvegarder les changements
- Lister les clients

2023-11-23 15:49 UTC, mgrati commented on galite-demo/galite-vaadin/src/main/kotlin/org/kopi/galite/demo/product/ProductForm.kt
Il n'est pas nécessaire d'avoir les champs uc et ts pour créer et utiliser un formulaire dans galite.

2023-11-23 15:53 UTC, mgrati commented on galite-core/src/main/kotlin/org/kopi/galite/visual/form/VBlock.kt
done

2023-11-23 15:53 UTC, mgrati commented on galite-core/src/main/resources/org/kopi/galite/visual/Messages-ar_TN.xml
done

2023-11-23 15:53 UTC, mgrati commented on galite-core/src/main/resources/org/kopi/galite/visual/Messages-de_AT.xml
done

2023-11-23 15:53 UTC, mgrati commented on galite-core/src/main/resources/org/kopi/galite/visual/Messages-en_GB.xml
done

2023-11-23 15:53 UTC, mgrati commented on galite-core/src/main/resources/org/kopi/galite/visual/Messages-fr_FR.xml
done

2023-11-24 11:21 UTC, RiadhCherni commented on galite-core/src/main/kotlin/org/kopi/galite/visual/ui/vaadin/calendar/DAbstractFullCalendar.kt
Le formulaire Task présente plusieurs anomalies ( ainsi que la class Calendar), comme j'ai mentionné précédemment. Il est nécessaire de créer un dossier spécifique pour traiter tous les problèmes.
exemple d'anomalie :
![Capture d’écran du 2023-11-24 12-14-50](https://github.com/kopiLeft/Galite/assets/58057058/e291e380-0efc-4816-a7a5-8121f1777b74)

autre anomalie :
java.lang.RuntimeException: org.kopi.galite.visual.ui.vaadin.calendar.DAbstractFullCalendar$updateEntries$1@d56abff Fetch entries

2023-11-24 11:28 UTC, RiadhCherni commented on galite-demo/galite-vaadin/src/main/kotlin/org/kopi/galite/demo/client/ClientForm.kt
j'arrive pas à ajouté un nouveau client :
![Capture d’écran du 2023-11-24 12-26-59](https://github.com/kopiLeft/Galite/assets/58057058/16940ac3-9cae-4b61-9ea8-e017e9ab018c)

Lorsque j'ai tenté d'ajouter un nouveau client avec ses ventes, j'ai rencontré cette erreur.
![Capture d’écran du 2023-11-24 12-23-36](https://github.com/kopiLeft/Galite/assets/58057058/eef07dc2-8e02-4300-84dd-42edbbc3914d)

2023-11-24 12:16 UTC, RiadhCherni commented on galite-demo/galite-vaadin/src/main/kotlin/org/kopi/galite/demo/product/ProductForm.kt
Ci-dessous le résultat du test : 
![Capture d’écran du 2023-11-24 13-15-51](https://github.com/kopiLeft/Galite/assets/58057058/31f8f003-fe56-43ab-be8f-8ea75d4164af)
log : Caused by: java.lang.AssertionError: UC or TS field must exist (Block = BlockProduct).
        at org.kopi.galite.visual.form.VBlock.insertRecord(VBlock.kt:3313)
        at org.kopi.galite.visual.form.VBlock.save(VBlock.kt:1893)
        at org.kopi.galite.visual.form.Commands$saveBlock$2.invoke(Commands.kt:373)
        at org.kopi.galite.visual.form.Commands$saveBlock$2.invoke(Commands.kt:372)
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction$run(ThreadLocalTransactionManager.kt:189)
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.access$inTopLevelTransaction$run(ThreadLocalTransactionManager.kt:1)
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$inTopLevelTransaction$1.invoke(ThreadLocalTransactionManager.kt:215)
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:223)
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:214)
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$transaction$1.invoke(ThreadLocalTransactionManager.kt:165)
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:223)
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:135)
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:132)
        at org.kopi.galite.visual.database.WindowTransactionKt$transaction$1.invoke(WindowTransaction.kt:79)
        at org.kopi.galite.visual.database.WindowTransactionKt.doAndWait(WindowTransaction.kt:124)
        at org.kopi.galite.visual.database.WindowTransactionKt.transaction(WindowTransaction.kt:78)
        at org.kopi.galite.visual.database.WindowTransactionKt.transaction$default(WindowTransaction.kt:75)
        at org.kopi.galite.visual.form.Commands.saveBlock(Commands.kt:372)
        ... 8 more

2023-11-24 15:03 UTC, RiadhCherni commented on galite-demo/galite-vaadin/src/main/kotlin/org/kopi/galite/demo/client/ClientForm.kt
https://github.com/kopiLeft/Galite/issues/609

2023-11-24 15:03 UTC, RiadhCherni commented on galite-demo/galite-vaadin/src/main/kotlin/org/kopi/galite/demo/product/ProductForm.kt
https://github.com/kopiLeft/Galite/issues/609

2023-11-24 15:05 UTC, RiadhCherni approved these changes

2023-11-27 14:00 UTC, merged