Implementation of the Pivot table component
kopiLeft/Galite pull request #606
Opened 2023-10-20 18:18 UTC by RiadhCherni

Add pivot table component to Galite

2023-11-09 14:16 UTC, mgrati commented on galite-core/src/main/kotlin/org/kopi/galite/visual/pivotTable/MPivotTable.kt
> + * Copyright (c) 1990-2022 kopiRight Managed Solutions GmbH, Wien AT
Replace `2022` with `2023`

2023-11-09 14:18 UTC, mgrati commented on galite-core/src/main/kotlin/org/kopi/galite/visual/pivotTable/MPivotTable.kt
> +  internal var userRows: ArrayList<VPivotTableRow>? = ArrayList(500)
Why is a limit of 500? What is the expected treatment when we have more than 500 data rows?

2023-11-09 14:26 UTC, mgrati commented on galite-core/src/main/kotlin/org/kopi/galite/visual/pivotTable/VHelpGenerator.kt
> + * Copyright (c) 1990-2022 kopiRight Managed Solutions GmbH, Wien AT
Replace `2022` with `2023`

2023-11-09 14:27 UTC, mgrati commented on galite-core/src/main/kotlin/org/kopi/galite/visual/pivotTable/VHelpGenerator.kt
> +                      help: String?): String? {
Fix indentation

2023-11-09 14:27 UTC, mgrati commented on galite-core/src/main/kotlin/org/kopi/galite/visual/pivotTable/VPivotTable.kt
> +import java.net.MalformedURLException
Order imports

2023-11-09 14:29 UTC, mgrati commented on galite-core/src/main/kotlin/org/kopi/galite/visual/pivotTable/VPivotTable.kt
> +  var pivottableType = Constants.DEFAULT_RENDERER  // Default pivot table type
rename `pivotTableType` with `defaultRenderer`

2023-11-09 14:30 UTC, mgrati commented on galite-core/src/main/kotlin/org/kopi/galite/visual/pivotTable/VPivotTable.kt
> +  }
why do we add a deprecated method to a new module?

2023-11-09 14:31 UTC, mgrati commented on galite-core/src/main/kotlin/org/kopi/galite/visual/pivotTable/VPivotTable.kt
> +  internal fun setType(type: String) {
Do we mean renderer by type? if so rename to `setDefaultRenderer`.

2023-11-09 14:35 UTC, mgrati commented on galite-core/src/main/kotlin/org/kopi/galite/visual/ui/vaadin/pivotTable/DPivotTable.kt
> +  private val listeDimensionColumns = mutableListOf<String>()
Rename `listeDimensionRows` to `rows`
Rename `listeDimensionColumns` to `columns`

2023-11-09 14:35 UTC, mgrati commented on galite-core/src/main/kotlin/org/kopi/galite/visual/ui/vaadin/pivotTable/DPivotTable.kt
> +      .forEach {
Remove new line & fix following indentation

2023-11-09 14:36 UTC, mgrati commented on galite-core/src/main/kotlin/org/kopi/galite/visual/ui/vaadin/pivotTable/DPivotTable.kt
> +      ?.chunked(model.columns.count()) { rows ->
Remove new lines & fix following indentation

2023-11-09 14:37 UTC, mgrati commented on galite-core/src/main/kotlin/org/kopi/galite/visual/ui/vaadin/pivotTable/DPivotTable.kt
> +    val pivotMode = if(pivotTable.interactive == 0) {
add space after if

2023-11-09 14:47 UTC, mgrati commented on galite-demo/galite-vaadin/src/main/kotlin/org/kopi/galite/demo/bill/BillForm.kt
In galite-demo, I suggest focusing on creating one pivot table that can show the maximum allowed functionalities developed in this module.

I think we can use the Client form to do this, with a report that gets data from tables `CLIENTS` and `PURCHASE`.

The pivot table can show us the purchases per client/ country / city ...
I also suggest for a better visibilty to add more data to these tables using org.kopi.galite.demo.database.Migration

2023-11-23 11:22 UTC, mgrati requested changes
I added few code style comments below. Please check.

The task `./gradlew test` is failed. please check and fix the failed tests. The failed test is in Class org.kopi.galite.tests.ui.vaadin.form.FormTests and it is caused by the changes in Migration.addProducts. You can fix it by extracting the first 4 records of the loop and start your loop from 4 

 I also think that some changes need to be done for Galite demo : 
- The products pivot table is OK, However, the pivot tables added for clients or bill products I don't find particularly meaningful.
- For the client pivot table, I suggest that you add a left join with the table purchase and maybe product so you can add quantity and price as measures. and at the same time check if dimensions and measures can accept null values.
- I think we can delete the bill product pivot table since it's not really meaningful

2023-11-24 08:32 UTC, RiadhCherni commented on galite-core/src/main/kotlin/org/kopi/galite/visual/dsl/pivottable/PivotTable.kt
> +
done

2023-11-24 08:33 UTC, RiadhCherni commented on galite-core/src/main/kotlin/org/kopi/galite/visual/pivottable/Constants.kt
> +import org.vaadin.addons.componentfactory.PivotTable.Aggregator
done

2023-11-24 08:34 UTC, RiadhCherni commented on galite-core/src/main/kotlin/org/kopi/galite/visual/pivottable/VPivotTable.kt
> +              model) as UPivotTable
done

2023-11-24 08:44 UTC, RiadhCherni commented on galite-core/src/main/kotlin/org/kopi/galite/visual/pivottable/VPivotTable.kt
> +import org.vaadin.addons.componentfactory.PivotTable.*
Dans l'ensemble du projet, les imports de galite précédent toujours les imports de vaadin.

2023-11-24 08:53 UTC, mgrati commented on galite-core/src/main/kotlin/org/kopi/galite/visual/pivottable/VPivotTable.kt
> +import org.vaadin.addons.componentfactory.PivotTable.*
That does not mean it's the right way. Please check our style guide references : http://mediawiki.dms.at/wiki/KOPI_Style_Guide#Package_and_Import_Statements 
![image](https://github.com/kopiLeft/Galite/assets/89453349/bcab885e-a263-458f-b370-fc077c94d814)

2023-11-24 11:06 UTC, RiadhCherni commented on galite-core/src/main/kotlin/org/kopi/galite/visual/dsl/pivottable/Dimension.kt
> +      COLUMN(Constants.DIMENSION_COLUMN),
done

2023-11-24 11:07 UTC, RiadhCherni commented on galite-core/src/main/kotlin/org/kopi/galite/visual/pivottable/VPivotTable.kt
> +import org.vaadin.addons.componentfactory.PivotTable.*
done

2023-11-24 16:33 UTC, mgrati approved these changes

2023-11-27 14:00 UTC, merged