Correct the handling of CodeDomain types in the pivot table
kopiLeft/Galite pull request #615
Opened 2023-12-20 14:19 UTC by Iyedchaabane

APPS-01X0 : Correct the handling of CodeDomain types in the pivot table

2023-12-25 13:34 UTC, RiadhCherni requested changes

2023-12-25 13:34 UTC, RiadhCherni commented on galite-core/src/main/kotlin/org/kopi/galite/visual/pivottable/MPivotTable.kt
Restaurer la ligne 34 : internal var userRows: ArrayList<VPivotTableRow>? = ArrayList()
et faire les changements nécessaires

2023-12-25 13:34 UTC, RiadhCherni commented on galite-core/src/main/kotlin/org/kopi/galite/visual/pivottable/VBooleanCodeColumn.kt
supprimer cette import : import org.kopi.galite.visual.report.VCellFormat
supprimer cette ligne format: VCellFormat? ( ligne 12 )
supprimer ligne 18

2023-12-25 13:34 UTC, RiadhCherni commented on galite-core/src/main/kotlin/org/kopi/galite/visual/pivottable/VBooleanColumn.kt
supprimer cette import : import org.kopi.galite.visual.report.VCellFormat
supprimer cette ligne format: VCellFormat? ( ligne 13 )
supprimer ligne 16

2023-12-25 13:34 UTC, RiadhCherni commented on galite-core/src/main/kotlin/org/kopi/galite/visual/pivottable/VCodeColumn.kt
supprimer cette import : import org.kopi.galite.visual.report.VCellFormat
supprimer cette ligne format: VCellFormat? ( ligne 35 )
supprimer ligne 39

Changer la méthode format  à : 
override fun format(o: Any?): String {
      return if (names != null) names!![getIndex(o)]!! else idents[getIndex(o)]
  }

2023-12-25 13:34 UTC, RiadhCherni commented on galite-core/src/main/kotlin/org/kopi/galite/visual/pivottable/VDecimalCodeColumn.kt
supprimer cette import : import org.kopi.galite.visual.report.VCellFormat
supprimer cette ligne format: VCellFormat? ( ligne 13 )
supprimer ligne 19

2023-12-25 13:34 UTC, RiadhCherni commented on galite-core/src/main/kotlin/org/kopi/galite/visual/pivottable/VDecimalColumn.kt
supprimer cette import : import org.kopi.galite.visual.report.VCellFormat
supprimer cette ligne format: VCellFormat? ( ligne 13 )
supprimer ligne 16

2023-12-25 13:34 UTC, RiadhCherni commented on galite-core/src/main/kotlin/org/kopi/galite/visual/pivottable/VIntegerCodeColumn.kt
supprimer cette import : import org.kopi.galite.visual.report.VCellFormat
supprimer cette ligne format: VCellFormat? ( ligne 11 )
supprimer ligne 17

2023-12-25 13:34 UTC, RiadhCherni commented on galite-core/src/main/kotlin/org/kopi/galite/visual/pivottable/VIntegerColumn.kt
supprimer cette import : import org.kopi.galite.visual.report.VCellFormat
supprimer cette ligne format: VCellFormat? ( ligne 8 )
supprimer ligne 11
supprimer les sauts de ligne ( ligne 12 et 13 )

2023-12-25 13:34 UTC, RiadhCherni commented on galite-core/src/main/kotlin/org/kopi/galite/visual/pivottable/VPivotTableColumn.kt
supprimer cette import : import org.kopi.galite.visual.report.VCellFormat
supprimer ligne 30
supprimer cette ligne format: VCellFormat? ( ligne 34 )
vérifier l'utilisation du méthode format 
A quoi sert le changement du méthode localize à open

2023-12-25 13:34 UTC, RiadhCherni commented on galite-core/src/main/kotlin/org/kopi/galite/visual/pivottable/VStringCodeColumn.kt
supprimer cette import : import org.kopi.galite.visual.report.VCellFormat
supprimer cette ligne format: VCellFormat? ( ligne 12 )
supprimer ligne 18

2023-12-25 13:34 UTC, RiadhCherni commented on galite-core/src/main/kotlin/org/kopi/galite/visual/pivottable/VStringColumn.kt
supprimer cette import : import org.kopi.galite.visual.report.VCellFormat
supprimer cette ligne format: VCellFormat? ( ligne 13 )
supprimer ligne 16
supprimer le saut de ligne ( ligne 17 )

2023-12-25 13:34 UTC, RiadhCherni commented on galite-core/src/main/kotlin/org/kopi/galite/visual/ui/vaadin/pivottable/DPivotTable.kt
Changer le nom du variable baseRows,
Changer le nom du fonction changeValue
Changer le nom du variable i par j et la variable j par i.

2023-12-26 11:37 UTC, Iyedchaabane commented on galite-core/src/main/kotlin/org/kopi/galite/visual/pivottable/VPivotTableColumn.kt
Par analogie avec VReportColumn, j'ajoute une nouvelle méthode ouverte nommée localize(parentLocalizer: FieldLocalizer) avec un corps vide. Cette dernière sera utilisée dans VCodeColumn .

2023-12-26 15:14 UTC, RiadhCherni requested changes

2023-12-26 15:14 UTC, RiadhCherni commented on galite-core/src/main/kotlin/org/kopi/galite/visual/pivottable/VBooleanCodeColumn.kt
Corriger l'indentation :
: VCodeColumn(ident,
            position,
            type,
            source,
            name) {

2023-12-26 15:14 UTC, RiadhCherni commented on galite-core/src/main/kotlin/org/kopi/galite/visual/pivottable/VCodeColumn.kt
changer ces deux lignes : 
 * Copyright (c) 2013-2022 kopiLeft Services SARL, Tunis TN
 * Copyright (c) 1990-2022 kopiRight Managed Solutions GmbH, Wien AT

2022 --> 2023

2023-12-26 15:14 UTC, RiadhCherni commented on galite-core/src/main/kotlin/org/kopi/galite/visual/pivottable/VBooleanColumn.kt
changer ces deux lignes : 
 * Copyright (c) 2013-2022 kopiLeft Services SARL, Tunis TN
 * Copyright (c) 1990-2022 kopiRight Managed Solutions GmbH, Wien AT

2022 --> 2023

2023-12-26 15:14 UTC, RiadhCherni commented on galite-core/src/main/kotlin/org/kopi/galite/visual/pivottable/VIntegerCodeColumn.kt
Corriger l'indentation : 
              : VCodeColumn(ident,
              position,
              type,
              source,
              name) {

2023-12-26 15:14 UTC, RiadhCherni commented on galite-core/src/main/kotlin/org/kopi/galite/visual/ui/vaadin/pivottable/DPivotTable.kt
Supprimer le saut de ligne ( ligne 46 )

2024-01-16 09:54 UTC, RiadhCherni approved these changes

2024-02-19 13:39 UTC, merged