Galite 01 xt
kopiLeft/Galite pull request #616
Opened 2023-12-25 13:53 UTC by sebai-dhia

fix issue 609

2023-12-25 14:32 UTC, RiadhCherni requested changes

2023-12-25 14:32 UTC, RiadhCherni commented on gradle.properties
Annuler les changements dans ce fichier

2023-12-26 15:05 UTC, RiadhCherni approved these changes

2023-12-26 15:05 UTC, RiadhCherni commented on gradle.properties
supprimer le saut de ligne ( ligne 5 )

2023-12-27 09:14 UTC, sebai-dhia commented on gradle.properties
c bon

2024-02-20 10:17 UTC, merged