adding classes LogoutModule, Module, RootMenu
kopiLeft/Galite pull request #63
Opened 2020-10-06 17:33 UTC by h-haddad

2020-10-08 14:17 UTC, SNsir requested changes

2020-10-13 08:39 UTC, SNsir approved these changes

2020-10-16 14:44 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/visual/Module.kt
> +             var access: Int,
change access to accessibility
`@param accessibility the access of the current user to the module`

2020-10-16 14:44 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/visual/Module.kt
> +  fun getSmallIcon(): Image? = smallIcon
remove and  change visibility of smallIcon property

2020-10-16 14:44 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/visual/Module.kt
> +   */
In this class, It will be better to move properties to begining of the class

2020-10-16 14:44 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/visual/Module.kt
> +  init {
move init after properties

2020-10-16 14:44 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/visual/Module.kt
> +    this.objectName = objectName!!
this will lead to NPE
object name could be nullable so dont add (!!)
also you can join initialization with property declaration

2020-10-16 14:44 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/visual/RootMenu.kt
> + * Present a root menu from its ID and name.
change class doc 
```
A root menu must provide its ID and name. The root tree node
of this menu should be provided for further uses.
```

2020-10-16 14:44 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/visual/RootMenu.kt
> +    get() = rootModule.id
getId()

2020-10-16 14:46 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/visual/RootMenu.kt
> +  }
move to begining of class and fix indentation

2020-10-16 14:46 UTC, hfazai commented on galite-core/src/main/kotlin/org/kopi/galite/visual/RootMenu.kt
> +  private val rootModule: Module
move to begining

2020-10-16 15:04 UTC, h-haddad commented on galite-core/src/main/kotlin/org/kopi/galite/visual/Module.kt
> + * @param objectName          the name of the object which are linked with the module
doc exist!

2020-10-18 18:04 UTC, merged