The Factory generation task does not meet the needs of the LSD project, as it treats null strings and empty strings the same way.
kopiLeft/Galite pull request #637
Opened 2024-09-18 11:05 UTC by yahiaoui97

The Factory generation task does not meet the needs of the LSD project, as it treats null strings and empty strings the same way.

2024-09-18 13:24 UTC, RiadhCherni requested changes

2024-09-18 13:24 UTC, RiadhCherni commented on galite-util/src/main/kotlin/org/kopi/galite/util/xsdToFactory/generator/FactoryGenerator.kt
> +    printer.print(factory, writer, options.getAbstract!!, options.lsdFactory ?: false)
Merci de changer 
"options.lsdFactory ?: false" à options.lsdFactory!!

2024-09-18 13:24 UTC, RiadhCherni commented on galite-util/src/main/kotlin/org/kopi/galite/util/xsdToFactory/options/FactoryGeneratorOptions.kt
Merci de changer l'initialisation du variable total à :
val total = arrayOfNulls<String>(parent.size + 7)

2024-09-18 13:24 UTC, RiadhCherni commented on galite-util/src/main/kotlin/org/kopi/galite/util/xsdToFactory/options/FactoryGeneratorOptions.kt
> +      total[parent.size + 6] = "  --lsdFactory, -a<boolean>: Generate methods for LSD Project"
Merci de changer "-a" à "-l"

2024-09-18 13:44 UTC, RiadhCherni approved these changes

2024-09-18 18:21 UTC, mgrati requested changes
We should rename the option lsdFactory. In fact, Galite is more general and shouldn't recognize LSD. We should give the option a significant name that indicate what is does : We can name it for example keepEmptyStrings.

2024-09-18 18:21 UTC, mgrati commented on gradle.properties
> +version=1.5.4-02DD
In the final branch to integrate, gradle.properties should stay inchanged.

2024-09-19 10:37 UTC, mgrati approved these changes
Approved changes.

2024-09-19 10:40 UTC, merged