adding classes VChart, VChartCommand
kopiLeft/Galite pull request #71
Opened 2020-10-09 11:19 UTC by h-haddad

2020-10-12 11:00 UTC, SNsir requested changes

2020-10-15 14:39 UTC, SNsir requested changes

2020-10-15 14:39 UTC, SNsir commented on galite-core/src/main/kotlin/org/kopi/galite/chart/VChart.kt
> +                                                       help)
fix indentation

2020-10-15 14:39 UTC, SNsir commented on galite-core/src/main/kotlin/org/kopi/galite/chart/VChartCommand.kt
> +  override fun helpOnCommand(help: org.kopi.galite.visual.VHelpGenerator) {
override fun helpOnCommand(help: VHelpGenerator) {

and add import org.kopi.galite.visual.VHelpGenerator

2020-10-21 10:28 UTC, h-haddad commented on galite-core/src/main/kotlin/org/kopi/galite/chart/VChart.kt
> + * @throws VException Visual errors.
we dont need to change this because we have : 
`import org.kopi.galite.visual.VException`

2020-10-21 10:32 UTC, h-haddad commented on galite-core/src/main/kotlin/org/kopi/galite/chart/VChart.kt
> +  override fun getType(): Int = Constants.MDL_CHART
We don't have a problem here because we have imported Constants, then when we need to use a _static var_ we put: **Constants. Xxx**

2020-10-21 10:32 UTC, h-haddad commented on galite-core/src/main/kotlin/org/kopi/galite/chart/VChart.kt
> +  open fun getDocumentType(): Int = Printable.DOC_UNKNOWN
same !

2020-10-21 10:33 UTC, h-haddad commented on galite-core/src/main/kotlin/org/kopi/galite/chart/VChart.kt
> +   * @throws VException Visual errors.
We have import in the beginning of the file

2020-10-21 10:37 UTC, h-haddad commented on galite-core/src/main/kotlin/org/kopi/galite/chart/VChart.kt
> +  open fun getFixedType(): VChartType? = callTrigger(CConstants.TRG_CHARTTYPE) as VChartType?
same !

2020-10-21 10:37 UTC, h-haddad commented on galite-core/src/main/kotlin/org/kopi/galite/chart/VChart.kt
> +      callTrigger(CConstants.TRG_POSTCHART)
same !

2020-10-21 10:41 UTC, h-haddad commented on galite-core/src/main/kotlin/org/kopi/galite/chart/VChart.kt
> +    setPageTitle(MessageFormat.format(pageTitle, *params))
to decompose the Array

2020-11-04 13:53 UTC, SNsir commented on galite-core/src/main/kotlin/org/kopi/galite/chart/VChart.kt
> +   * Returns true iff there is trigger associated with given event.
if*

2020-11-04 14:00 UTC, SNsir requested changes

2020-11-05 08:39 UTC, SNsir approved these changes

2020-11-05 11:06 UTC, merged