adding VStringCodeField, VStringField
kopiLeft/Galite pull request #74
Opened 2020-10-09 16:33 UTC by h-haddad

2020-10-13 16:23 UTC, ZMarouani requested changes

2020-10-13 16:23 UTC, ZMarouani commented on galite-core/src/main/kotlin/org/kopi/galite/form/VStringField.kt
> +  constructor(width: Int, height: Int, convert: Int, styled: Boolean) : this(width, height, 0, convert, styled) {}
Remove empty {}

2020-10-13 16:23 UTC, ZMarouani commented on galite-core/src/main/kotlin/org/kopi/galite/form/VStringField.kt
> +    end = textToModel(s, width, Int.MAX_VALUE).length
Empty line

2020-10-13 16:23 UTC, ZMarouani commented on galite-core/src/main/kotlin/org/kopi/galite/form/VStringField.kt
> +    // TODO Auto-generated method stub
is it for todo or is it not?

2020-10-19 14:27 UTC, ZMarouani requested changes

2020-10-19 14:27 UTC, ZMarouani commented on galite-core/src/main/kotlin/org/kopi/galite/form/VStringField.kt
> +  }
= (o as String?).orEmpty()

2020-10-19 14:27 UTC, ZMarouani commented on galite-core/src/main/kotlin/org/kopi/galite/form/VStringField.kt
> +
Del

2020-10-20 09:06 UTC, h-haddad commented on galite-core/src/main/kotlin/org/kopi/galite/form/VStringField.kt
> +  }
```
private fun convertName(source: String): String {
    val chars = source.toLowerCase().toCharArray()
    var found = false

    for (i in chars.indices) {
      if (!found && chars[i].isLetter()) {
        chars[i] = chars[i].toUpperCase()
        found = true
      } else if (chars[i].isWhitespace()) {
        found = false
      }
    }
    return String(chars)
  }
```

2020-10-21 09:15 UTC, ZMarouani approved these changes

2020-11-02 15:56 UTC, merged