adding VListDialog, VMonthField classes
kopiLeft/Galite pull request #78
Opened 2020-10-15 16:35 UTC by h-haddad

2020-10-16 16:36 UTC, SNsir commented on galite-core/src/main/kotlin/org/kopi/galite/form/VListDialog.kt
> +              value1 > (value2 as String?)!!
(value2 as String)

2020-10-19 10:01 UTC, SNsir requested changes

2020-10-19 10:44 UTC, SNsir requested changes

2020-10-19 10:44 UTC, SNsir commented on galite-core/src/main/kotlin/org/kopi/galite/form/VField.kt
>     * Warning:   This method will become inaccessible to kopi users in next release
remove kopi

2020-10-19 10:44 UTC, SNsir commented on galite-core/src/main/kotlin/org/kopi/galite/form/VListDialog.kt
> +                  val rows: Int,
rows is not a property

2020-10-19 10:44 UTC, SNsir commented on galite-core/src/main/kotlin/org/kopi/galite/form/VListDialog.kt
> +                                            arrayOf<Array<String>>(data) as Array<Array<Any>>,
check cast

2020-10-19 10:44 UTC, SNsir commented on galite-core/src/main/kotlin/org/kopi/galite/form/VListDialog.kt
> +              value1 > (value2 as String?)!!
value2 as? String

2020-10-19 10:44 UTC, SNsir commented on galite-core/src/main/kotlin/org/kopi/galite/form/VListDialog.kt
> +    }
if possible change it to forEach

2020-10-19 10:44 UTC, SNsir commented on galite-core/src/main/kotlin/org/kopi/galite/form/VListDialog.kt
> +    }
if possible change it to forEach

2020-10-19 10:44 UTC, SNsir commented on galite-core/src/main/kotlin/org/kopi/galite/form/VMonthField.kt
> +    }
elvis operator

2020-10-20 15:16 UTC, h-haddad commented on galite-core/src/main/kotlin/org/kopi/galite/form/VListDialog.kt
> +    }
no because we cant do : 
it = ...

2020-10-20 15:16 UTC, h-haddad commented on galite-core/src/main/kotlin/org/kopi/galite/form/VListDialog.kt
> +    }
we cant

2020-10-20 15:47 UTC, h-haddad commented on galite-core/src/main/kotlin/org/kopi/galite/form/VMonthField.kt
> +    }
cannot

2020-10-21 10:12 UTC, SNsir approved these changes

2020-11-06 16:50 UTC, merged