adding methods in VMenuTree with Exposed & create DBSchema
kopiLeft/Galite pull request #85
Opened 2020-10-26 08:12 UTC by h-haddad

2020-11-03 13:59 UTC, ZMarouani requested changes

2020-11-03 13:59 UTC, ZMarouani commented on galite-core/src/main/kotlin/org/kopi/galite/visual/VMenuTree.kt
> +        val id = UserRights.select { UserRights.id eq 0 }.single()[UserRights.id]
Should this be in this if {} ?

2020-11-04 11:15 UTC, h-haddad commented on galite-core/src/main/kotlin/org/kopi/galite/visual/VMenuTree.kt
> +          icon = Symbols.select { Symbols.id eq symbol }.single()[Symbols.objectName]
I do not develop this class just I added exposed

2020-11-04 11:19 UTC, h-haddad commented on galite-core/src/main/kotlin/org/kopi/galite/visual/VMenuTree.kt
> +                it[Modules.objectName],
No this method is used in Query class

2020-11-04 14:30 UTC, h-haddad commented on galite-core/src/main/kotlin/org/kopi/galite/visual/VMenuTree.kt
I do not develop this class just I added exposed

2020-11-06 13:30 UTC, ZMarouani approved these changes

2020-11-06 13:33 UTC, merged